#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("in_angle_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("in_angle_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("in_angle_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("in_angle_TKEEP", 4, hls_in, 1, "axis", "in_data", 1),
	Port_Property("in_angle_TSTRB", 4, hls_in, 2, "axis", "in_data", 1),
	Port_Property("in_angle_TUSER", 2, hls_in, 3, "axis", "in_data", 1),
	Port_Property("in_angle_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("in_angle_TID", 5, hls_in, 5, "axis", "in_data", 1),
	Port_Property("in_angle_TDEST", 6, hls_in, 6, "axis", "in_data", 1),
	Port_Property("in_distance_TDATA", 32, hls_in, 7, "axis", "in_data", 1),
	Port_Property("in_distance_TVALID", 1, hls_in, 13, "axis", "in_vld", 1),
	Port_Property("in_distance_TREADY", 1, hls_out, 13, "axis", "in_acc", 1),
	Port_Property("in_distance_TKEEP", 4, hls_in, 8, "axis", "in_data", 1),
	Port_Property("in_distance_TSTRB", 4, hls_in, 9, "axis", "in_data", 1),
	Port_Property("in_distance_TUSER", 2, hls_in, 10, "axis", "in_data", 1),
	Port_Property("in_distance_TLAST", 1, hls_in, 11, "axis", "in_data", 1),
	Port_Property("in_distance_TID", 5, hls_in, 12, "axis", "in_data", 1),
	Port_Property("in_distance_TDEST", 6, hls_in, 13, "axis", "in_data", 1),
	Port_Property("out_clusters_TDATA", 32, hls_out, 14, "axis", "out_data", 1),
	Port_Property("out_clusters_TVALID", 1, hls_out, 20, "axis", "out_vld", 1),
	Port_Property("out_clusters_TREADY", 1, hls_in, 20, "axis", "out_acc", 1),
	Port_Property("out_clusters_TKEEP", 4, hls_out, 15, "axis", "out_data", 1),
	Port_Property("out_clusters_TSTRB", 4, hls_out, 16, "axis", "out_data", 1),
	Port_Property("out_clusters_TUSER", 2, hls_out, 17, "axis", "out_data", 1),
	Port_Property("out_clusters_TLAST", 1, hls_out, 18, "axis", "out_data", 1),
	Port_Property("out_clusters_TID", 5, hls_out, 19, "axis", "out_data", 1),
	Port_Property("out_clusters_TDEST", 6, hls_out, 20, "axis", "out_data", 1),
};
const char* HLS_Design_Meta::dut_name = "clusterOp";
