#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Mar 27 21:42:58 -0400 2023
# SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm lib_pkg_v1_0_2 fifo_generator_v13_2_7 lib_fifo_v1_0_16 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_29 axi_sg_v4_1_15 axi_dma_v7_1_28 xil_defaultlib axi_infrastructure_v1_1_0 axi_vip_v1_1_13 processing_system7_vip_v1_0_15 proc_sys_reset_v5_0_13 xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_18 floating_point_v7_1_15 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_27 axi_data_fifo_v2_1_26 axi_crossbar_v2_1_28 axi_protocol_converter_v2_1_27 axi_clock_converter_v2_1_26 blk_mem_gen_v8_4_5 axi_dwidth_converter_v2_1_27)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "E:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "E:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "E:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "E:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_16 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6c82/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_29 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/2237/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_15 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/751a/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_28 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/70c4/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_dma_0/sim/design_1_axi_dma_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_15 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/364f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_18 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ab19/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_15 $vhdlan_opts \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/22f8/hdl/floating_point_v7_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work floating_point_v7_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/22f8/hdl/floating_point_v7_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_clusterOp_Pipeline_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_clusterOp_Pipeline_VITIS_LOOP_27_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_clusterOp_Pipeline_VITIS_LOOP_42_3.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_clusterOp_Pipeline_VITIS_LOOP_67_5.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_clusters_id_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_clusters_members_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_CTRL_BUS_s_axi.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_distances_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_exp_core_32_32_66_s.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_exp_core_32_32_66_s_exp_x_msb_1_table_V_ROM_AUTO_1R.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_exp_core_32_32_66_s_f_x_msb_2_table_V_ROM_AUTO_1R.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_exp_core_32_32_66_s_f_x_msb_3_table_V_ROM_AUTO_1R.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_exp_core_32_32_66_s_f_x_msb_4_table_V_ROM_AUTO_1R.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_exp_core_32_32_66_s_f_x_msb_5_table_V_ROM_AUTO_1R.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_fcmp_32ns_32ns_1_2_no_dsp_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_flow_control_loop_pipe_sequential_init.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_grouped_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_hls_deadlock_idx0_monitor.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_log_99_33_s.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_log_99_33_s_log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_ROM_AUTbkb.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_log_99_33_s_log_apfixed_reduce_log_inverse_lut_table_array_V_ROM_AUTO_1R.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_log_99_33_s_log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_ROM_AUTOcud.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_log_99_33_s_log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_ROM_AUTOdEe.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_log_99_33_s_log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_ROM_AUTeOg.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_log_99_33_s_log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_ROM_AUTfYi.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_log_99_33_s_log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_ROM_AUTg8j.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_7s_83ns_88_5_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_29ns_29ns_58_2_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_32ns_8ns_40_2_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_51ns_50ns_101_5_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_60ns_6ns_66_5_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_65ns_6ns_71_5_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_67ns_63ns_130_5_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_70ns_6ns_76_5_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_72ns_68ns_140_5_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_75ns_6ns_81_5_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_81ns_4ns_85_5_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_110s_6ns_110_5_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_mul_17s_9ns_17_4_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_mul_mul_25ns_8ns_33_4_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_pow_32_32_s.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_regslice_both.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_sitofp_32ns_32_6_no_dsp_1.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp_sqrt_fixed_32_32_s.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog/clusterOp.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/ip/clusterOp_fcmp_32ns_32ns_1_2_no_dsp_1_ip.v" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/ip/clusterOp_sitofp_32ns_32_6_no_dsp_1_ip.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clusterOp_0_0/sim/design_1_clusterOp_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/c40e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/aeb3/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/b8be/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/4675/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ipshared/6a0a/hdl/verilog" +incdir+"$ref_dir/../../../../clusterOp_2022.1.gen/sources_1/bd/design_1/ip/design_1_clusterOp_0_0/drivers/clusterOp_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_0/sim/design_1_auto_us_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_2/sim/design_1_auto_pc_2.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
