// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module clusterOp_log_99_33_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_state1 = 51'd1;
parameter    ap_ST_fsm_state2 = 51'd2;
parameter    ap_ST_fsm_state3 = 51'd4;
parameter    ap_ST_fsm_state4 = 51'd8;
parameter    ap_ST_fsm_state5 = 51'd16;
parameter    ap_ST_fsm_state6 = 51'd32;
parameter    ap_ST_fsm_state7 = 51'd64;
parameter    ap_ST_fsm_state8 = 51'd128;
parameter    ap_ST_fsm_state9 = 51'd256;
parameter    ap_ST_fsm_state10 = 51'd512;
parameter    ap_ST_fsm_state11 = 51'd1024;
parameter    ap_ST_fsm_state12 = 51'd2048;
parameter    ap_ST_fsm_state13 = 51'd4096;
parameter    ap_ST_fsm_state14 = 51'd8192;
parameter    ap_ST_fsm_state15 = 51'd16384;
parameter    ap_ST_fsm_state16 = 51'd32768;
parameter    ap_ST_fsm_state17 = 51'd65536;
parameter    ap_ST_fsm_state18 = 51'd131072;
parameter    ap_ST_fsm_state19 = 51'd262144;
parameter    ap_ST_fsm_state20 = 51'd524288;
parameter    ap_ST_fsm_state21 = 51'd1048576;
parameter    ap_ST_fsm_state22 = 51'd2097152;
parameter    ap_ST_fsm_state23 = 51'd4194304;
parameter    ap_ST_fsm_state24 = 51'd8388608;
parameter    ap_ST_fsm_state25 = 51'd16777216;
parameter    ap_ST_fsm_state26 = 51'd33554432;
parameter    ap_ST_fsm_state27 = 51'd67108864;
parameter    ap_ST_fsm_state28 = 51'd134217728;
parameter    ap_ST_fsm_state29 = 51'd268435456;
parameter    ap_ST_fsm_state30 = 51'd536870912;
parameter    ap_ST_fsm_state31 = 51'd1073741824;
parameter    ap_ST_fsm_state32 = 51'd2147483648;
parameter    ap_ST_fsm_state33 = 51'd4294967296;
parameter    ap_ST_fsm_state34 = 51'd8589934592;
parameter    ap_ST_fsm_state35 = 51'd17179869184;
parameter    ap_ST_fsm_state36 = 51'd34359738368;
parameter    ap_ST_fsm_state37 = 51'd68719476736;
parameter    ap_ST_fsm_state38 = 51'd137438953472;
parameter    ap_ST_fsm_state39 = 51'd274877906944;
parameter    ap_ST_fsm_state40 = 51'd549755813888;
parameter    ap_ST_fsm_state41 = 51'd1099511627776;
parameter    ap_ST_fsm_state42 = 51'd2199023255552;
parameter    ap_ST_fsm_state43 = 51'd4398046511104;
parameter    ap_ST_fsm_state44 = 51'd8796093022208;
parameter    ap_ST_fsm_state45 = 51'd17592186044416;
parameter    ap_ST_fsm_state46 = 51'd35184372088832;
parameter    ap_ST_fsm_state47 = 51'd70368744177664;
parameter    ap_ST_fsm_state48 = 51'd140737488355328;
parameter    ap_ST_fsm_state49 = 51'd281474976710656;
parameter    ap_ST_fsm_state50 = 51'd562949953421312;
parameter    ap_ST_fsm_state51 = 51'd1125899906842624;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [98:0] x;
output  [71:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[71:0] ap_return;

(* fsm_encoding = "none" *) reg   [50:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] log_apfixed_reduce_log_inverse_lut_table_array_V_address0;
reg    log_apfixed_reduce_log_inverse_lut_table_array_V_ce0;
wire   [5:0] log_apfixed_reduce_log_inverse_lut_table_array_V_q0;
wire   [5:0] log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_address0;
reg    log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_ce0;
wire   [81:0] log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_q0;
wire   [3:0] log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_address0;
reg    log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_ce0;
wire   [77:0] log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_q0;
wire   [5:0] log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_address0;
reg    log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_ce0;
wire   [74:0] log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_q0;
wire   [5:0] log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_address0;
reg    log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_ce0;
wire   [69:0] log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_q0;
wire   [5:0] log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_address0;
reg    log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_ce0;
wire   [64:0] log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_q0;
wire   [5:0] log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_address0;
reg    log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_ce0;
wire   [59:0] log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_q0;
wire   [0:0] icmp_ln1652_fu_413_p2;
reg   [0:0] icmp_ln1652_reg_1305;
wire   [109:0] p_Result_100_fu_423_p4;
wire   [0:0] icmp_ln731_fu_459_p2;
reg   [0:0] icmp_ln731_reg_1314;
wire  signed [6:0] b_exp_V_3_fu_478_p2;
reg  signed [6:0] b_exp_V_3_reg_1332;
wire    ap_CS_fsm_state2;
reg   [108:0] p_Val2_34_reg_1338;
wire    ap_CS_fsm_state3;
wire   [109:0] r_V_13_fu_487_p3;
reg   [109:0] r_V_13_reg_1343;
wire   [0:0] p_Result_s_fu_501_p3;
reg   [0:0] p_Result_s_reg_1349;
wire   [0:0] select_ln731_fu_547_p3;
reg   [81:0] trunc_ln1_reg_1361;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln541_fu_604_p1;
reg   [63:0] zext_ln541_reg_1367;
wire    ap_CS_fsm_state8;
reg   [5:0] b_frac_tilde_inverse_V_reg_1377;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [3:0] a_V_reg_1387;
wire    ap_CS_fsm_state14;
reg   [80:0] tmp_30_reg_1393;
reg   [0:0] tmp_38_reg_1399;
reg   [79:0] tmp_31_reg_1404;
reg   [76:0] tmp_33_reg_1409;
wire   [85:0] select_ln1488_fu_684_p3;
reg   [85:0] select_ln1488_reg_1414;
wire    ap_CS_fsm_state15;
wire   [84:0] grp_fu_697_p2;
reg   [84:0] r_V_14_reg_1429;
wire    ap_CS_fsm_state19;
reg   [74:0] tmp_34_reg_1434;
wire    ap_CS_fsm_state20;
reg   [68:0] tmp_35_reg_1440;
reg   [5:0] tmp_36_reg_1445;
wire    ap_CS_fsm_state21;
wire   [80:0] grp_fu_764_p2;
reg   [80:0] r_V_15_reg_1461;
wire    ap_CS_fsm_state25;
reg   [69:0] tmp_37_reg_1466;
wire    ap_CS_fsm_state26;
reg   [63:0] tmp_39_reg_1472;
reg   [5:0] tmp_40_reg_1477;
wire    ap_CS_fsm_state27;
wire   [75:0] grp_fu_851_p2;
reg   [75:0] r_V_16_reg_1493;
wire    ap_CS_fsm_state31;
reg   [64:0] tmp_41_reg_1498;
wire    ap_CS_fsm_state32;
reg   [58:0] tmp_42_reg_1504;
reg   [5:0] tmp_43_reg_1509;
wire    ap_CS_fsm_state33;
wire   [70:0] grp_fu_938_p2;
reg   [70:0] r_V_17_reg_1525;
wire    ap_CS_fsm_state37;
reg   [59:0] tmp_44_reg_1530;
wire    ap_CS_fsm_state38;
reg   [53:0] tmp_45_reg_1536;
reg   [5:0] tmp_46_reg_1541;
wire    ap_CS_fsm_state39;
wire   [65:0] grp_fu_1025_p2;
reg   [65:0] r_V_18_reg_1557;
wire    ap_CS_fsm_state43;
reg   [54:0] tmp_47_reg_1562;
wire    ap_CS_fsm_state44;
reg   [28:0] tmp_48_reg_1567;
wire   [57:0] zext_ln1270_fu_1096_p1;
wire    ap_CS_fsm_state45;
wire    ap_CS_fsm_state46;
reg   [56:0] rhs_s_reg_1608;
reg   [77:0] logn_V_reg_1613;
wire    ap_CS_fsm_state47;
reg   [69:0] logn_V_2_reg_1618;
reg  signed [55:0] trunc_ln818_2_reg_1623;
wire   [65:0] add_ln813_fu_1177_p2;
reg   [65:0] add_ln813_reg_1629;
wire  signed [81:0] add_ln813_3_fu_1183_p2;
reg  signed [81:0] add_ln813_3_reg_1634;
wire   [77:0] add_ln813_2_fu_1215_p2;
reg   [77:0] add_ln813_2_reg_1640;
wire    ap_CS_fsm_state48;
wire   [88:0] add_ln813_4_fu_1224_p2;
reg   [88:0] add_ln813_4_reg_1646;
wire   [87:0] add_ln813_7_fu_1239_p2;
reg   [87:0] add_ln813_7_reg_1651;
reg   [0:0] p_Result_101_reg_1656;
wire    ap_CS_fsm_state49;
reg   [71:0] r_V_11_reg_1661;
wire    ap_CS_fsm_state50;
reg   [81:0] ap_phi_mux_conv_i_i_i38032_phi_fu_353_p4;
reg   [81:0] conv_i_i_i38032_reg_349;
reg   [109:0] ap_phi_mux_b_frac_013_lcssa29_phi_fu_364_p4;
reg   [109:0] b_frac_013_lcssa29_reg_361;
reg   [5:0] ap_phi_mux_index0_V_2_phi_fu_374_p4;
reg   [81:0] conv_i_i_i38031_reg_380;
reg  signed [109:0] r_V_reg_391;
reg   [71:0] ap_phi_mux_r_V_12_phi_fu_406_p4;
reg   [71:0] r_V_12_reg_402;
wire    ap_CS_fsm_state51;
wire   [63:0] zext_ln541_1_fu_1105_p1;
wire   [63:0] zext_ln541_2_fu_1109_p1;
wire   [63:0] zext_ln541_3_fu_1113_p1;
wire   [63:0] zext_ln541_4_fu_1117_p1;
wire   [63:0] zext_ln541_5_fu_1121_p1;
reg   [108:0] p_Val2_33_fu_244;
wire   [108:0] shl_ln1453_fu_495_p2;
wire   [108:0] p_Result_117_cast_fu_433_p3;
reg   [6:0] b_exp_V_fu_248;
wire   [97:0] trunc_ln594_fu_419_p1;
wire   [1:0] tmp_s_fu_441_p4;
wire   [108:0] and_ln_fu_451_p3;
wire   [1:0] tmp_29_fu_509_p4;
wire   [108:0] and_ln731_1_fu_519_p3;
wire   [0:0] tmp_fu_533_p3;
wire   [0:0] xor_ln731_fu_541_p2;
wire   [0:0] icmp_ln731_1_fu_527_p2;
wire   [82:0] grp_fu_567_p1;
wire   [87:0] grp_fu_567_p2;
wire   [5:0] grp_fu_612_p1;
wire   [109:0] grp_fu_612_p2;
wire   [84:0] zext_ln1488_cast_fu_666_p3;
wire   [85:0] tmp_32_fu_673_p3;
wire   [85:0] zext_ln1488_fu_680_p1;
wire   [80:0] grp_fu_697_p0;
wire   [3:0] grp_fu_697_p1;
wire   [84:0] lhs_fu_703_p3;
wire   [85:0] zext_ln1347_fu_710_p1;
wire   [85:0] ret_V_11_fu_714_p2;
wire   [85:0] zext_ln1348_fu_719_p1;
wire   [85:0] ret_V_2_fu_722_p2;
wire   [74:0] grp_fu_764_p0;
wire   [5:0] grp_fu_764_p1;
wire   [82:0] lhs_2_fu_777_p3;
wire   [82:0] eZ_fu_770_p3;
wire   [83:0] zext_ln1347_1_fu_784_p1;
wire   [83:0] zext_ln813_fu_788_p1;
wire   [81:0] rhs_3_fu_798_p3;
wire   [83:0] ret_V_12_fu_792_p2;
wire   [83:0] zext_ln1348_1_fu_805_p1;
wire   [83:0] ret_V_4_fu_809_p2;
wire   [69:0] grp_fu_851_p0;
wire   [5:0] grp_fu_851_p1;
wire   [87:0] lhs_4_fu_864_p3;
wire   [82:0] eZ_1_fu_857_p3;
wire   [88:0] zext_ln1347_2_fu_871_p1;
wire   [88:0] zext_ln813_1_fu_875_p1;
wire   [81:0] rhs_6_fu_885_p3;
wire   [88:0] ret_V_13_fu_879_p2;
wire   [88:0] zext_ln1348_2_fu_892_p1;
wire   [88:0] ret_V_6_fu_896_p2;
wire   [64:0] grp_fu_938_p0;
wire   [5:0] grp_fu_938_p1;
wire   [92:0] lhs_6_fu_951_p3;
wire   [82:0] eZ_2_fu_944_p3;
wire   [93:0] zext_ln1347_3_fu_958_p1;
wire   [93:0] zext_ln813_2_fu_962_p1;
wire   [81:0] rhs_9_fu_972_p3;
wire   [93:0] ret_V_14_fu_966_p2;
wire   [93:0] zext_ln1348_3_fu_979_p1;
wire   [93:0] ret_V_8_fu_983_p2;
wire   [59:0] grp_fu_1025_p0;
wire   [5:0] grp_fu_1025_p1;
wire   [97:0] lhs_8_fu_1038_p3;
wire   [82:0] eZ_3_fu_1031_p3;
wire   [98:0] zext_ln1347_4_fu_1045_p1;
wire   [98:0] zext_ln813_3_fu_1049_p1;
wire   [81:0] rhs_12_fu_1059_p3;
wire   [98:0] ret_V_15_fu_1053_p2;
wire   [98:0] zext_ln1348_4_fu_1066_p1;
wire   [98:0] ret_V_10_fu_1070_p2;
wire   [28:0] grp_fu_1099_p0;
wire   [28:0] grp_fu_1099_p1;
wire   [57:0] grp_fu_1099_p2;
wire   [84:0] lhs_V_fu_1147_p3;
wire   [85:0] zext_ln1348_5_fu_1154_p1;
wire   [85:0] zext_ln1348_6_fu_1158_p1;
wire   [85:0] ret_V_fu_1161_p2;
wire   [65:0] zext_ln387_3_fu_1143_p1;
wire   [65:0] zext_ln387_2_fu_1139_p1;
wire   [81:0] zext_ln387_fu_1135_p1;
wire  signed [87:0] shl_ln_fu_1195_p3;
wire   [77:0] zext_ln387_1_fu_1189_p1;
wire   [77:0] add_ln813_1_fu_1210_p2;
wire   [77:0] zext_ln813_4_fu_1207_p1;
wire  signed [88:0] sext_ln813_fu_1203_p1;
wire  signed [88:0] sext_ln818_fu_1192_p1;
wire  signed [87:0] sext_ln813_2_fu_1221_p1;
wire   [87:0] add_ln813_5_fu_1233_p2;
wire  signed [87:0] sext_ln813_3_fu_1230_p1;
wire  signed [88:0] sext_ln813_1_fu_1248_p1;
wire   [88:0] add_ln813_6_fu_1251_p2;
wire   [88:0] zext_ln813_5_fu_1245_p1;
wire   [88:0] log_base_V_2_fu_1256_p2;
wire   [87:0] zext_ln813_6_fu_1270_p1;
wire   [16:0] shl_ln813_1_fu_1278_p3;
wire   [87:0] add_ln778_fu_1273_p2;
wire  signed [87:0] sext_ln813_4_fu_1285_p1;
wire   [87:0] log_base_V_fu_1289_p2;
reg   [71:0] ap_return_preg;
reg   [50:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire   [65:0] grp_fu_1025_p00;
wire   [65:0] grp_fu_1025_p10;
wire   [109:0] grp_fu_612_p10;
wire   [84:0] grp_fu_697_p00;
wire   [84:0] grp_fu_697_p10;
wire   [80:0] grp_fu_764_p00;
wire   [80:0] grp_fu_764_p10;
wire   [75:0] grp_fu_851_p00;
wire   [75:0] grp_fu_851_p10;
wire   [70:0] grp_fu_938_p00;
wire   [70:0] grp_fu_938_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 51'd1;
#0 ap_return_preg = 72'd0;
end

clusterOp_log_99_33_s_log_apfixed_reduce_log_inverse_lut_table_array_V_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
log_apfixed_reduce_log_inverse_lut_table_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log_inverse_lut_table_array_V_address0),
    .ce0(log_apfixed_reduce_log_inverse_lut_table_array_V_ce0),
    .q0(log_apfixed_reduce_log_inverse_lut_table_array_V_q0)
);

clusterOp_log_99_33_s_log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_ROM_AUTbkb #(
    .DataWidth( 82 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_address0),
    .ce0(log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_ce0),
    .q0(log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_q0)
);

clusterOp_log_99_33_s_log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_ROM_AUTOcud #(
    .DataWidth( 78 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_address0),
    .ce0(log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_ce0),
    .q0(log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_q0)
);

clusterOp_log_99_33_s_log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_ROM_AUTOdEe #(
    .DataWidth( 75 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_address0),
    .ce0(log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_ce0),
    .q0(log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_q0)
);

clusterOp_log_99_33_s_log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_ROM_AUTeOg #(
    .DataWidth( 70 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_address0),
    .ce0(log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_ce0),
    .q0(log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_q0)
);

clusterOp_log_99_33_s_log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_ROM_AUTfYi #(
    .DataWidth( 65 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_address0),
    .ce0(log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_ce0),
    .q0(log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_q0)
);

clusterOp_log_99_33_s_log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_ROM_AUTg8j #(
    .DataWidth( 60 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_address0),
    .ce0(log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_ce0),
    .q0(log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_q0)
);

clusterOp_mul_7s_83ns_88_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 83 ),
    .dout_WIDTH( 88 ))
mul_7s_83ns_88_5_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_exp_V_3_reg_1332),
    .din1(grp_fu_567_p1),
    .ce(1'b1),
    .dout(grp_fu_567_p2)
);

clusterOp_mul_110s_6ns_110_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 110 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 110 ))
mul_110s_6ns_110_5_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_V_reg_391),
    .din1(grp_fu_612_p1),
    .ce(1'b1),
    .dout(grp_fu_612_p2)
);

clusterOp_mul_81ns_4ns_85_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 81 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 85 ))
mul_81ns_4ns_85_5_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_697_p0),
    .din1(grp_fu_697_p1),
    .ce(1'b1),
    .dout(grp_fu_697_p2)
);

clusterOp_mul_75ns_6ns_81_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 75 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 81 ))
mul_75ns_6ns_81_5_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_764_p0),
    .din1(grp_fu_764_p1),
    .ce(1'b1),
    .dout(grp_fu_764_p2)
);

clusterOp_mul_70ns_6ns_76_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 70 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 76 ))
mul_70ns_6ns_76_5_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_851_p0),
    .din1(grp_fu_851_p1),
    .ce(1'b1),
    .dout(grp_fu_851_p2)
);

clusterOp_mul_65ns_6ns_71_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 65 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 71 ))
mul_65ns_6ns_71_5_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_938_p0),
    .din1(grp_fu_938_p1),
    .ce(1'b1),
    .dout(grp_fu_938_p2)
);

clusterOp_mul_60ns_6ns_66_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 60 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 66 ))
mul_60ns_6ns_66_5_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1025_p0),
    .din1(grp_fu_1025_p1),
    .ce(1'b1),
    .dout(grp_fu_1025_p2)
);

clusterOp_mul_29ns_29ns_58_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 29 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 58 ))
mul_29ns_29ns_58_2_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1099_p0),
    .din1(grp_fu_1099_p1),
    .ce(1'b1),
    .dout(grp_fu_1099_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 72'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state51)) begin
            ap_return_preg <= ap_phi_mux_r_V_12_phi_fu_406_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln731_fu_459_p2 == 1'd0) & (icmp_ln1652_fu_413_p2 == 1'd0))) begin
        b_exp_V_fu_248 <= 7'd32;
    end else if (((1'b1 == ap_CS_fsm_state3) & (select_ln731_fu_547_p3 == 1'd0))) begin
        b_exp_V_fu_248 <= b_exp_V_3_reg_1332;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln731_fu_459_p2 == 1'd1) & (icmp_ln1652_fu_413_p2 == 1'd0))) begin
                b_frac_013_lcssa29_reg_361[109 : 11] <= p_Result_100_fu_423_p4[109 : 11];
    end else if (((1'b1 == ap_CS_fsm_state8) & (p_Result_s_reg_1349 == 1'd0) & (icmp_ln731_reg_1314 == 1'd0))) begin
                b_frac_013_lcssa29_reg_361[109 : 11] <= r_V_13_reg_1343[109 : 11];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        if (((p_Result_s_reg_1349 == 1'd0) | (icmp_ln731_reg_1314 == 1'd1))) begin
            conv_i_i_i38031_reg_380 <= ap_phi_mux_conv_i_i_i38032_phi_fu_353_p4;
        end else if (((p_Result_s_reg_1349 == 1'd1) & (icmp_ln731_reg_1314 == 1'd0))) begin
            conv_i_i_i38031_reg_380 <= trunc_ln1_reg_1361;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln731_fu_459_p2 == 1'd1) & (icmp_ln1652_fu_413_p2 == 1'd0))) begin
        conv_i_i_i38032_reg_349 <= 82'd1675927046744002482639815;
    end else if (((1'b1 == ap_CS_fsm_state8) & (p_Result_s_reg_1349 == 1'd0) & (icmp_ln731_reg_1314 == 1'd0))) begin
        conv_i_i_i38032_reg_349 <= trunc_ln1_reg_1361;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln731_fu_459_p2 == 1'd0) & (icmp_ln1652_fu_413_p2 == 1'd0))) begin
                p_Val2_33_fu_244[108 : 11] <= p_Result_117_cast_fu_433_p3[108 : 11];
    end else if (((1'b1 == ap_CS_fsm_state3) & (select_ln731_fu_547_p3 == 1'd0))) begin
                p_Val2_33_fu_244[108 : 11] <= shl_ln1453_fu_495_p2[108 : 11];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1652_fu_413_p2 == 1'd1))) begin
        r_V_12_reg_402 <= 72'd0;
    end else if (((1'b1 == ap_CS_fsm_state51) & (icmp_ln1652_reg_1305 == 1'd0))) begin
        r_V_12_reg_402 <= r_V_11_reg_1661;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        if (((p_Result_s_reg_1349 == 1'd0) | (icmp_ln731_reg_1314 == 1'd1))) begin
                        r_V_reg_391[109 : 11] <= ap_phi_mux_b_frac_013_lcssa29_phi_fu_364_p4[109 : 11];
        end else if (((p_Result_s_reg_1349 == 1'd1) & (icmp_ln731_reg_1314 == 1'd0))) begin
                        r_V_reg_391[109 : 11] <= r_V_13_reg_1343[109 : 11];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        a_V_reg_1387 <= {{grp_fu_612_p2[109:106]}};
        tmp_30_reg_1393 <= {{grp_fu_612_p2[109:29]}};
        tmp_31_reg_1404 <= {{grp_fu_612_p2[109:30]}};
        tmp_33_reg_1409 <= {{grp_fu_612_p2[105:29]}};
        tmp_38_reg_1399 <= grp_fu_612_p2[32'd109];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        add_ln813_2_reg_1640 <= add_ln813_2_fu_1215_p2;
        add_ln813_4_reg_1646 <= add_ln813_4_fu_1224_p2;
        add_ln813_7_reg_1651 <= add_ln813_7_fu_1239_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        add_ln813_3_reg_1634 <= add_ln813_3_fu_1183_p2;
        add_ln813_reg_1629 <= add_ln813_fu_1177_p2;
        logn_V_2_reg_1618 <= log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_q0;
        logn_V_reg_1613 <= log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_q0;
        trunc_ln818_2_reg_1623 <= {{ret_V_fu_1161_p2[85:30]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        b_exp_V_3_reg_1332 <= b_exp_V_3_fu_478_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        b_frac_tilde_inverse_V_reg_1377 <= log_apfixed_reduce_log_inverse_lut_table_array_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln1652_reg_1305 <= icmp_ln1652_fu_413_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1652_fu_413_p2 == 1'd0))) begin
        icmp_ln731_reg_1314 <= icmp_ln731_fu_459_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        p_Result_101_reg_1656 <= log_base_V_2_fu_1256_p2[32'd88];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_Result_s_reg_1349 <= p_Val2_33_fu_244[32'd108];
        p_Val2_34_reg_1338[108 : 11] <= p_Val2_33_fu_244[108 : 11];
        r_V_13_reg_1343[109 : 12] <= r_V_13_fu_487_p3[109 : 12];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        r_V_11_reg_1661 <= {{log_base_V_fu_1289_p2[87:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        r_V_14_reg_1429 <= grp_fu_697_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        r_V_15_reg_1461 <= grp_fu_764_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        r_V_16_reg_1493 <= grp_fu_851_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        r_V_17_reg_1525 <= grp_fu_938_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        r_V_18_reg_1557 <= grp_fu_1025_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        rhs_s_reg_1608 <= {{grp_fu_1099_p2[57:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        select_ln1488_reg_1414[80 : 0] <= select_ln1488_fu_684_p3[80 : 0];
select_ln1488_reg_1414[85 : 84] <= select_ln1488_fu_684_p3[85 : 84];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        tmp_34_reg_1434 <= {{ret_V_2_fu_722_p2[85:11]}};
        tmp_35_reg_1440 <= {{ret_V_2_fu_722_p2[79:11]}};
        tmp_36_reg_1445 <= {{ret_V_2_fu_722_p2[85:80]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        tmp_37_reg_1466 <= {{ret_V_4_fu_809_p2[83:14]}};
        tmp_39_reg_1472 <= {{ret_V_4_fu_809_p2[77:14]}};
        tmp_40_reg_1477 <= {{ret_V_4_fu_809_p2[83:78]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        tmp_41_reg_1498 <= {{ret_V_6_fu_896_p2[88:24]}};
        tmp_42_reg_1504 <= {{ret_V_6_fu_896_p2[82:24]}};
        tmp_43_reg_1509 <= {{ret_V_6_fu_896_p2[88:83]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        tmp_44_reg_1530 <= {{ret_V_8_fu_983_p2[93:34]}};
        tmp_45_reg_1536 <= {{ret_V_8_fu_983_p2[87:34]}};
        tmp_46_reg_1541 <= {{ret_V_8_fu_983_p2[93:88]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        tmp_47_reg_1562 <= {{ret_V_10_fu_1070_p2[98:44]}};
        tmp_48_reg_1567 <= {{ret_V_10_fu_1070_p2[98:70]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        trunc_ln1_reg_1361 <= {{grp_fu_567_p2[87:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        zext_ln541_reg_1367[5 : 0] <= zext_ln541_fu_604_p1[5 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (p_Result_s_reg_1349 == 1'd0) & (icmp_ln731_reg_1314 == 1'd0))) begin
        ap_phi_mux_b_frac_013_lcssa29_phi_fu_364_p4 = r_V_13_reg_1343;
    end else begin
        ap_phi_mux_b_frac_013_lcssa29_phi_fu_364_p4 = b_frac_013_lcssa29_reg_361;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (p_Result_s_reg_1349 == 1'd0) & (icmp_ln731_reg_1314 == 1'd0))) begin
        ap_phi_mux_conv_i_i_i38032_phi_fu_353_p4 = trunc_ln1_reg_1361;
    end else begin
        ap_phi_mux_conv_i_i_i38032_phi_fu_353_p4 = conv_i_i_i38032_reg_349;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        if (((p_Result_s_reg_1349 == 1'd0) | (icmp_ln731_reg_1314 == 1'd1))) begin
            ap_phi_mux_index0_V_2_phi_fu_374_p4 = {{ap_phi_mux_b_frac_013_lcssa29_phi_fu_364_p4[107:102]}};
        end else if (((p_Result_s_reg_1349 == 1'd1) & (icmp_ln731_reg_1314 == 1'd0))) begin
            ap_phi_mux_index0_V_2_phi_fu_374_p4 = {{p_Val2_34_reg_1338[107:102]}};
        end else begin
            ap_phi_mux_index0_V_2_phi_fu_374_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_index0_V_2_phi_fu_374_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) & (icmp_ln1652_reg_1305 == 1'd0))) begin
        ap_phi_mux_r_V_12_phi_fu_406_p4 = r_V_11_reg_1661;
    end else begin
        ap_phi_mux_r_V_12_phi_fu_406_p4 = r_V_12_reg_402;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        ap_return = ap_phi_mux_r_V_12_phi_fu_406_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        log_apfixed_reduce_log_inverse_lut_table_array_V_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log_inverse_lut_table_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln731_fu_459_p2 == 1'd0) & (icmp_ln1652_fu_413_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln731_fu_459_p2 == 1'd1) & (icmp_ln1652_fu_413_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1652_fu_413_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (select_ln731_fu_547_p3 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln778_fu_1273_p2 = (add_ln813_7_reg_1651 + zext_ln813_6_fu_1270_p1);

assign add_ln813_1_fu_1210_p2 = (zext_ln387_1_fu_1189_p1 + logn_V_reg_1613);

assign add_ln813_2_fu_1215_p2 = (add_ln813_1_fu_1210_p2 + zext_ln813_4_fu_1207_p1);

assign add_ln813_3_fu_1183_p2 = (zext_ln387_fu_1135_p1 + log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_q0);

assign add_ln813_4_fu_1224_p2 = ($signed(sext_ln813_fu_1203_p1) + $signed(sext_ln818_fu_1192_p1));

assign add_ln813_5_fu_1233_p2 = ($signed(shl_ln_fu_1195_p3) + $signed(sext_ln813_2_fu_1221_p1));

assign add_ln813_6_fu_1251_p2 = ($signed(add_ln813_4_reg_1646) + $signed(sext_ln813_1_fu_1248_p1));

assign add_ln813_7_fu_1239_p2 = ($signed(add_ln813_5_fu_1233_p2) + $signed(sext_ln813_3_fu_1230_p1));

assign add_ln813_fu_1177_p2 = (zext_ln387_3_fu_1143_p1 + zext_ln387_2_fu_1139_p1);

assign and_ln731_1_fu_519_p3 = {{tmp_29_fu_509_p4}, {107'd0}};

assign and_ln_fu_451_p3 = {{tmp_s_fu_441_p4}, {107'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign b_exp_V_3_fu_478_p2 = ($signed(b_exp_V_fu_248) + $signed(7'd127));

assign eZ_1_fu_857_p3 = {{13'd4096}, {tmp_37_reg_1466}};

assign eZ_2_fu_944_p3 = {{18'd131072}, {tmp_41_reg_1498}};

assign eZ_3_fu_1031_p3 = {{23'd4194304}, {tmp_44_reg_1530}};

assign eZ_fu_770_p3 = {{8'd128}, {tmp_34_reg_1434}};

assign grp_fu_1025_p0 = grp_fu_1025_p00;

assign grp_fu_1025_p00 = tmp_44_reg_1530;

assign grp_fu_1025_p1 = grp_fu_1025_p10;

assign grp_fu_1025_p10 = tmp_46_reg_1541;

assign grp_fu_1099_p0 = zext_ln1270_fu_1096_p1;

assign grp_fu_1099_p1 = zext_ln1270_fu_1096_p1;

assign grp_fu_567_p1 = 88'd3351854093488004965279630;

assign grp_fu_612_p1 = grp_fu_612_p10;

assign grp_fu_612_p10 = b_frac_tilde_inverse_V_reg_1377;

assign grp_fu_697_p0 = grp_fu_697_p00;

assign grp_fu_697_p00 = tmp_30_reg_1393;

assign grp_fu_697_p1 = grp_fu_697_p10;

assign grp_fu_697_p10 = a_V_reg_1387;

assign grp_fu_764_p0 = grp_fu_764_p00;

assign grp_fu_764_p00 = tmp_34_reg_1434;

assign grp_fu_764_p1 = grp_fu_764_p10;

assign grp_fu_764_p10 = tmp_36_reg_1445;

assign grp_fu_851_p0 = grp_fu_851_p00;

assign grp_fu_851_p00 = tmp_37_reg_1466;

assign grp_fu_851_p1 = grp_fu_851_p10;

assign grp_fu_851_p10 = tmp_40_reg_1477;

assign grp_fu_938_p0 = grp_fu_938_p00;

assign grp_fu_938_p00 = tmp_41_reg_1498;

assign grp_fu_938_p1 = grp_fu_938_p10;

assign grp_fu_938_p10 = tmp_43_reg_1509;

assign icmp_ln1652_fu_413_p2 = (($signed(x) < $signed(99'd1)) ? 1'b1 : 1'b0);

assign icmp_ln731_1_fu_527_p2 = ((and_ln731_1_fu_519_p3 == 109'd486777830487640090174734030864384) ? 1'b1 : 1'b0);

assign icmp_ln731_fu_459_p2 = ((and_ln_fu_451_p3 == 109'd486777830487640090174734030864384) ? 1'b1 : 1'b0);

assign lhs_2_fu_777_p3 = {{tmp_35_reg_1440}, {14'd0}};

assign lhs_4_fu_864_p3 = {{tmp_39_reg_1472}, {24'd0}};

assign lhs_6_fu_951_p3 = {{tmp_42_reg_1504}, {34'd0}};

assign lhs_8_fu_1038_p3 = {{tmp_45_reg_1536}, {44'd0}};

assign lhs_V_fu_1147_p3 = {{tmp_47_reg_1562}, {30'd0}};

assign lhs_fu_703_p3 = {{tmp_33_reg_1409}, {8'd0}};

assign log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_V_address0 = zext_ln541_reg_1367;

assign log_apfixed_reduce_log_inverse_lut_table_array_V_address0 = zext_ln541_fu_604_p1;

assign log_apfixed_reduce_log_lut_table_ap_fixed_12_6_64_array_V_address0 = zext_ln541_3_fu_1113_p1;

assign log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_address0 = zext_ln541_4_fu_1117_p1;

assign log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_address0 = zext_ln541_5_fu_1121_p1;

assign log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_V_address0 = zext_ln541_1_fu_1105_p1;

assign log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_address0 = zext_ln541_2_fu_1109_p1;

assign log_base_V_2_fu_1256_p2 = (add_ln813_6_fu_1251_p2 + zext_ln813_5_fu_1245_p1);

assign log_base_V_fu_1289_p2 = ($signed(add_ln778_fu_1273_p2) + $signed(sext_ln813_4_fu_1285_p1));

assign p_Result_100_fu_423_p4 = {{{{1'd0}, {trunc_ln594_fu_419_p1}}}, {11'd0}};

assign p_Result_117_cast_fu_433_p3 = {{trunc_ln594_fu_419_p1}, {11'd0}};

assign p_Result_s_fu_501_p3 = p_Val2_33_fu_244[32'd108];

assign r_V_13_fu_487_p3 = {{p_Val2_33_fu_244}, {1'd0}};

assign ret_V_10_fu_1070_p2 = (ret_V_15_fu_1053_p2 - zext_ln1348_4_fu_1066_p1);

assign ret_V_11_fu_714_p2 = (zext_ln1347_fu_710_p1 + select_ln1488_reg_1414);

assign ret_V_12_fu_792_p2 = (zext_ln1347_1_fu_784_p1 + zext_ln813_fu_788_p1);

assign ret_V_13_fu_879_p2 = (zext_ln1347_2_fu_871_p1 + zext_ln813_1_fu_875_p1);

assign ret_V_14_fu_966_p2 = (zext_ln1347_3_fu_958_p1 + zext_ln813_2_fu_962_p1);

assign ret_V_15_fu_1053_p2 = (zext_ln1347_4_fu_1045_p1 + zext_ln813_3_fu_1049_p1);

assign ret_V_2_fu_722_p2 = (ret_V_11_fu_714_p2 - zext_ln1348_fu_719_p1);

assign ret_V_4_fu_809_p2 = (ret_V_12_fu_792_p2 - zext_ln1348_1_fu_805_p1);

assign ret_V_6_fu_896_p2 = (ret_V_13_fu_879_p2 - zext_ln1348_2_fu_892_p1);

assign ret_V_8_fu_983_p2 = (ret_V_14_fu_966_p2 - zext_ln1348_3_fu_979_p1);

assign ret_V_fu_1161_p2 = (zext_ln1348_5_fu_1154_p1 - zext_ln1348_6_fu_1158_p1);

assign rhs_12_fu_1059_p3 = {{r_V_18_reg_1557}, {16'd0}};

assign rhs_3_fu_798_p3 = {{r_V_15_reg_1461}, {1'd0}};

assign rhs_6_fu_885_p3 = {{r_V_16_reg_1493}, {6'd0}};

assign rhs_9_fu_972_p3 = {{r_V_17_reg_1525}, {11'd0}};

assign select_ln1488_fu_684_p3 = ((tmp_38_reg_1399[0:0] == 1'b1) ? tmp_32_fu_673_p3 : zext_ln1488_fu_680_p1);

assign select_ln731_fu_547_p3 = ((p_Result_s_fu_501_p3[0:0] == 1'b1) ? xor_ln731_fu_541_p2 : icmp_ln731_1_fu_527_p2);

assign sext_ln813_1_fu_1248_p1 = add_ln813_3_reg_1634;

assign sext_ln813_2_fu_1221_p1 = trunc_ln818_2_reg_1623;

assign sext_ln813_3_fu_1230_p1 = add_ln813_3_reg_1634;

assign sext_ln813_4_fu_1285_p1 = $signed(shl_ln813_1_fu_1278_p3);

assign sext_ln813_fu_1203_p1 = shl_ln_fu_1195_p3;

assign sext_ln818_fu_1192_p1 = trunc_ln818_2_reg_1623;

assign shl_ln1453_fu_495_p2 = p_Val2_33_fu_244 << 109'd1;

assign shl_ln813_1_fu_1278_p3 = {{p_Result_101_reg_1656}, {16'd32768}};

assign shl_ln_fu_1195_p3 = {{conv_i_i_i38031_reg_380}, {6'd0}};

assign tmp_29_fu_509_p4 = {{p_Val2_33_fu_244[107:106]}};

assign tmp_32_fu_673_p3 = {{5'd16}, {tmp_30_reg_1393}};

assign tmp_fu_533_p3 = p_Val2_33_fu_244[32'd107];

assign tmp_s_fu_441_p4 = {{x[97:96]}};

assign trunc_ln594_fu_419_p1 = x[97:0];

assign xor_ln731_fu_541_p2 = (tmp_fu_533_p3 ^ 1'd1);

assign zext_ln1270_fu_1096_p1 = tmp_48_reg_1567;

assign zext_ln1347_1_fu_784_p1 = lhs_2_fu_777_p3;

assign zext_ln1347_2_fu_871_p1 = lhs_4_fu_864_p3;

assign zext_ln1347_3_fu_958_p1 = lhs_6_fu_951_p3;

assign zext_ln1347_4_fu_1045_p1 = lhs_8_fu_1038_p3;

assign zext_ln1347_fu_710_p1 = lhs_fu_703_p3;

assign zext_ln1348_1_fu_805_p1 = rhs_3_fu_798_p3;

assign zext_ln1348_2_fu_892_p1 = rhs_6_fu_885_p3;

assign zext_ln1348_3_fu_979_p1 = rhs_9_fu_972_p3;

assign zext_ln1348_4_fu_1066_p1 = rhs_12_fu_1059_p3;

assign zext_ln1348_5_fu_1154_p1 = lhs_V_fu_1147_p3;

assign zext_ln1348_6_fu_1158_p1 = rhs_s_reg_1608;

assign zext_ln1348_fu_719_p1 = r_V_14_reg_1429;

assign zext_ln1488_cast_fu_666_p3 = {{5'd16}, {tmp_31_reg_1404}};

assign zext_ln1488_fu_680_p1 = zext_ln1488_cast_fu_666_p3;

assign zext_ln387_1_fu_1189_p1 = logn_V_2_reg_1618;

assign zext_ln387_2_fu_1139_p1 = log_apfixed_reduce_log_lut_table_ap_fixed_17_6_64_array_V_q0;

assign zext_ln387_3_fu_1143_p1 = log_apfixed_reduce_log_lut_table_ap_fixed_22_6_64_array_V_q0;

assign zext_ln387_fu_1135_p1 = log_apfixed_reduce_log_lut_table_ap_fixed_7_6_64_array_V_q0;

assign zext_ln541_1_fu_1105_p1 = a_V_reg_1387;

assign zext_ln541_2_fu_1109_p1 = tmp_36_reg_1445;

assign zext_ln541_3_fu_1113_p1 = tmp_40_reg_1477;

assign zext_ln541_4_fu_1117_p1 = tmp_43_reg_1509;

assign zext_ln541_5_fu_1121_p1 = tmp_46_reg_1541;

assign zext_ln541_fu_604_p1 = ap_phi_mux_index0_V_2_phi_fu_374_p4;

assign zext_ln813_1_fu_875_p1 = eZ_1_fu_857_p3;

assign zext_ln813_2_fu_962_p1 = eZ_2_fu_944_p3;

assign zext_ln813_3_fu_1049_p1 = eZ_3_fu_1031_p3;

assign zext_ln813_4_fu_1207_p1 = add_ln813_reg_1629;

assign zext_ln813_5_fu_1245_p1 = add_ln813_2_reg_1640;

assign zext_ln813_6_fu_1270_p1 = add_ln813_2_reg_1640;

assign zext_ln813_fu_788_p1 = eZ_fu_770_p3;

always @ (posedge ap_clk) begin
    p_Val2_34_reg_1338[10:0] <= 11'b00000000000;
    r_V_13_reg_1343[11:0] <= 12'b000000000000;
    zext_ln541_reg_1367[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    select_ln1488_reg_1414[83:81] <= 3'b000;
    b_frac_013_lcssa29_reg_361[10:0] <= 11'b00000000000;
    r_V_reg_391[10:0] <= 11'b00000000000;
    p_Val2_33_fu_244[10:0] <= 11'b00000000000;
end

endmodule //clusterOp_log_99_33_s
