-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity clusterOp2_dbscan is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    data_ce0 : OUT STD_LOGIC;
    data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    visited_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    visited_ce0 : OUT STD_LOGIC;
    visited_we0 : OUT STD_LOGIC;
    visited_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    visited_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    clusters_id_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    clusters_id_ce0 : OUT STD_LOGIC;
    clusters_id_we0 : OUT STD_LOGIC;
    clusters_id_d0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    clusters_members_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    clusters_members_ce0 : OUT STD_LOGIC;
    clusters_members_we0 : OUT STD_LOGIC;
    clusters_members_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    clusters_member_count_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    clusters_member_count_ce0 : OUT STD_LOGIC;
    clusters_member_count_we0 : OUT STD_LOGIC;
    clusters_member_count_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of clusterOp2_dbscan is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (20 downto 0) := "000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (20 downto 0) := "000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (20 downto 0) := "000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (20 downto 0) := "000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (20 downto 0) := "000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (20 downto 0) := "000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (20 downto 0) := "000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (20 downto 0) := "000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (20 downto 0) := "000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (20 downto 0) := "001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (20 downto 0) := "010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (20 downto 0) := "100000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_168 : STD_LOGIC_VECTOR (8 downto 0) := "101101000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv17_168 : STD_LOGIC_VECTOR (16 downto 0) := "00000000101101000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal sin_values_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal sin_values_ce0 : STD_LOGIC;
    signal sin_values_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal cos_values_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal cos_values_ce0 : STD_LOGIC;
    signal cos_values_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_285 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal reg_289 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_293 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln103_fu_316_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln103_reg_495 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln103_fu_322_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln103_reg_500 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln103_fu_310_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal visited_addr_reg_507 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln103_fu_327_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln103_reg_512 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal visited_load_reg_517 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln97_fu_331_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal sext_ln98_fu_341_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_335_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln97_reg_546 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_345_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln98_reg_551 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln125_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln125_reg_556 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal cluster_count_0_load_reg_560 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln130_fu_364_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln130_reg_571 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln126_fu_368_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln126_reg_576 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_fu_457_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln150_reg_581 : STD_LOGIC_VECTOR (16 downto 0);
    signal clusters_member_count_addr_reg_586 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln130_fu_383_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln130_reg_594 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal icmp_ln130_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neighbors_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal neighbor_id_reg_604 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal zext_ln133_fu_402_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln133_reg_610 : STD_LOGIC_VECTOR (63 downto 0);
    signal visited_addr_1_reg_617 : STD_LOGIC_VECTOR (8 downto 0);
    signal visited_load_1_reg_622 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal grp_fu_411_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln97_2_reg_651 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal grp_fu_421_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln98_2_reg_656 : STD_LOGIC_VECTOR (31 downto 0);
    signal neighbors_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal neighbors_ce0 : STD_LOGIC;
    signal neighbors_we0 : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_start : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_done : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_idle : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_ready : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_data_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_data_ce0 : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_ce0 : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_we0 : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_d0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbor_count_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbor_count_out_ap_vld : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_sin_values_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_sin_values_ce0 : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_cos_values_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_cos_values_ce0 : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_335_p_din0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_335_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_335_p_ce : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_345_p_din0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_345_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_345_p_ce : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_sqrt_fixed_32_32_s_fu_664_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_start : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_done : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_idle : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_ready : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_data_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_data_ce0 : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_new_neighbor_count_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_new_neighbor_count_out_ap_vld : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_sin_values_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_sin_values_ce0 : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_cos_values_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_cos_values_ce0 : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_335_p_din0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_335_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_335_p_ce : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_345_p_din0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_345_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_345_p_ce : STD_LOGIC;
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_sqrt_fixed_32_32_s_fu_664_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sqrt_fixed_32_32_s_fu_664_x : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sqrt_fixed_32_32_s_fu_664_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal k_reg_214 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal inc5139_reg_225 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_inc512_phi_fu_242_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln150_fu_436_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal inc512_reg_238 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln149_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal zext_ln126_fu_373_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln130_fu_389_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln150_fu_452_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_58 : STD_LOGIC_VECTOR (8 downto 0);
    signal cluster_count_0_fu_62 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_335_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_335_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_345_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_345_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln150_1_fu_443_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln150_1_fu_447_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln150_1_fu_447_p2 : signal is "no";
    signal grp_fu_457_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_457_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_335_ce : STD_LOGIC;
    signal grp_fu_345_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component clusterOp2_dbscan_Pipeline_VITIS_LOOP_113_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        i : IN STD_LOGIC_VECTOR (8 downto 0);
        data_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        data_ce0 : OUT STD_LOGIC;
        data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mul_ln97 : IN STD_LOGIC_VECTOR (31 downto 0);
        mul_ln98 : IN STD_LOGIC_VECTOR (31 downto 0);
        neighbors_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        neighbors_ce0 : OUT STD_LOGIC;
        neighbors_we0 : OUT STD_LOGIC;
        neighbors_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        neighbor_count_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        neighbor_count_out_ap_vld : OUT STD_LOGIC;
        sin_values_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        sin_values_ce0 : OUT STD_LOGIC;
        sin_values_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
        cos_values_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        cos_values_ce0 : OUT STD_LOGIC;
        cos_values_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
        grp_fu_335_p_din0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        grp_fu_335_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_335_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_335_p_ce : OUT STD_LOGIC;
        grp_fu_345_p_din0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        grp_fu_345_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_345_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_345_p_ce : OUT STD_LOGIC;
        grp_sqrt_fixed_32_32_s_fu_664_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_sqrt_fixed_32_32_s_fu_664_p_dout0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component clusterOp2_dbscan_Pipeline_VITIS_LOOP_137_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        neighbor_id : IN STD_LOGIC_VECTOR (8 downto 0);
        data_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        data_ce0 : OUT STD_LOGIC;
        data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mul_ln97_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        mul_ln98_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        new_neighbor_count_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        new_neighbor_count_out_ap_vld : OUT STD_LOGIC;
        sin_values_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        sin_values_ce0 : OUT STD_LOGIC;
        sin_values_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
        cos_values_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        cos_values_ce0 : OUT STD_LOGIC;
        cos_values_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
        grp_fu_335_p_din0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        grp_fu_335_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_335_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_335_p_ce : OUT STD_LOGIC;
        grp_fu_345_p_din0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        grp_fu_345_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_345_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_345_p_ce : OUT STD_LOGIC;
        grp_sqrt_fixed_32_32_s_fu_664_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_sqrt_fixed_32_32_s_fu_664_p_dout0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component clusterOp2_sqrt_fixed_32_32_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        x : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component clusterOp2_mul_18s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component clusterOp2_mul_mul_17s_9ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component clusterOp2_dbscan_sin_values_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component clusterOp2_dbscan_cos_values_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component clusterOp2_dbscan_neighbors_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (8 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;



begin
    sin_values_U : component clusterOp2_dbscan_sin_values_ROM_AUTO_1R
    generic map (
        DataWidth => 18,
        AddressRange => 360,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sin_values_address0,
        ce0 => sin_values_ce0,
        q0 => sin_values_q0);

    cos_values_U : component clusterOp2_dbscan_cos_values_ROM_AUTO_1R
    generic map (
        DataWidth => 18,
        AddressRange => 360,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => cos_values_address0,
        ce0 => cos_values_ce0,
        q0 => cos_values_q0);

    neighbors_U : component clusterOp2_dbscan_neighbors_RAM_AUTO_1R1W
    generic map (
        DataWidth => 9,
        AddressRange => 360,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => neighbors_address0,
        ce0 => neighbors_ce0,
        we0 => neighbors_we0,
        d0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_d0,
        q0 => neighbors_q0);

    grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253 : component clusterOp2_dbscan_Pipeline_VITIS_LOOP_113_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_start,
        ap_done => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_done,
        ap_idle => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_idle,
        ap_ready => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_ready,
        i => i_fu_58,
        data_address0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_data_address0,
        data_ce0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_data_ce0,
        data_q0 => data_q0,
        mul_ln97 => mul_ln97_reg_546,
        mul_ln98 => mul_ln98_reg_551,
        neighbors_address0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_address0,
        neighbors_ce0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_ce0,
        neighbors_we0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_we0,
        neighbors_d0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_d0,
        neighbor_count_out => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbor_count_out,
        neighbor_count_out_ap_vld => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbor_count_out_ap_vld,
        sin_values_address0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_sin_values_address0,
        sin_values_ce0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_sin_values_ce0,
        sin_values_q0 => sin_values_q0,
        cos_values_address0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_cos_values_address0,
        cos_values_ce0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_cos_values_ce0,
        cos_values_q0 => cos_values_q0,
        grp_fu_335_p_din0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_335_p_din0,
        grp_fu_335_p_din1 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_335_p_din1,
        grp_fu_335_p_dout0 => grp_fu_335_p2,
        grp_fu_335_p_ce => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_335_p_ce,
        grp_fu_345_p_din0 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_345_p_din0,
        grp_fu_345_p_din1 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_345_p_din1,
        grp_fu_345_p_dout0 => grp_fu_345_p2,
        grp_fu_345_p_ce => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_345_p_ce,
        grp_sqrt_fixed_32_32_s_fu_664_p_din1 => grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_sqrt_fixed_32_32_s_fu_664_p_din1,
        grp_sqrt_fixed_32_32_s_fu_664_p_dout0 => grp_sqrt_fixed_32_32_s_fu_664_ap_return);

    grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268 : component clusterOp2_dbscan_Pipeline_VITIS_LOOP_137_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_start,
        ap_done => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_done,
        ap_idle => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_idle,
        ap_ready => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_ready,
        neighbor_id => neighbor_id_reg_604,
        data_address0 => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_data_address0,
        data_ce0 => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_data_ce0,
        data_q0 => data_q0,
        mul_ln97_2 => mul_ln97_2_reg_651,
        mul_ln98_2 => mul_ln98_2_reg_656,
        new_neighbor_count_out => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_new_neighbor_count_out,
        new_neighbor_count_out_ap_vld => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_new_neighbor_count_out_ap_vld,
        sin_values_address0 => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_sin_values_address0,
        sin_values_ce0 => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_sin_values_ce0,
        sin_values_q0 => sin_values_q0,
        cos_values_address0 => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_cos_values_address0,
        cos_values_ce0 => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_cos_values_ce0,
        cos_values_q0 => cos_values_q0,
        grp_fu_335_p_din0 => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_335_p_din0,
        grp_fu_335_p_din1 => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_335_p_din1,
        grp_fu_335_p_dout0 => grp_fu_335_p2,
        grp_fu_335_p_ce => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_335_p_ce,
        grp_fu_345_p_din0 => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_345_p_din0,
        grp_fu_345_p_din1 => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_345_p_din1,
        grp_fu_345_p_dout0 => grp_fu_345_p2,
        grp_fu_345_p_ce => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_345_p_ce,
        grp_sqrt_fixed_32_32_s_fu_664_p_din1 => grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_sqrt_fixed_32_32_s_fu_664_p_din1,
        grp_sqrt_fixed_32_32_s_fu_664_p_dout0 => grp_sqrt_fixed_32_32_s_fu_664_ap_return);

    grp_sqrt_fixed_32_32_s_fu_664 : component clusterOp2_sqrt_fixed_32_32_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x => grp_sqrt_fixed_32_32_s_fu_664_x,
        ap_return => grp_sqrt_fixed_32_32_s_fu_664_ap_return);

    mul_18s_32s_32_2_1_U37 : component clusterOp2_mul_18s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 18,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_335_p0,
        din1 => grp_fu_335_p1,
        ce => grp_fu_335_ce,
        dout => grp_fu_335_p2);

    mul_18s_32s_32_2_1_U38 : component clusterOp2_mul_18s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 18,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_345_p0,
        din1 => grp_fu_345_p1,
        ce => grp_fu_345_ce,
        dout => grp_fu_345_p2);

    mul_18s_32s_32_2_1_U39 : component clusterOp2_mul_18s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 18,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_289,
        din1 => reg_285,
        ce => ap_const_logic_1,
        dout => grp_fu_411_p2);

    mul_18s_32s_32_2_1_U40 : component clusterOp2_mul_18s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 18,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_293,
        din1 => reg_285,
        ce => ap_const_logic_1,
        dout => grp_fu_421_p2);

    mul_mul_17s_9ns_17_4_1_U41 : component clusterOp2_mul_mul_17s_9ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 9,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_457_p0,
        din1 => grp_fu_457_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_457_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_ready = ap_const_logic_1)) then 
                    grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                    grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_ready = ap_const_logic_1)) then 
                    grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    cluster_count_0_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                cluster_count_0_fu_62 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state13) and (icmp_ln130_fu_378_p2 = ap_const_lv1_1) and (icmp_ln125_reg_556 = ap_const_lv1_1) and (visited_load_reg_517 = ap_const_lv1_0))) then 
                cluster_count_0_fu_62 <= add_ln126_reg_576;
            end if; 
        end if;
    end process;

    i_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_58 <= ap_const_lv9_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state13) and ((visited_load_reg_517 = ap_const_lv1_1) or ((icmp_ln130_fu_378_p2 = ap_const_lv1_1) or (icmp_ln125_reg_556 = ap_const_lv1_0))))) then 
                i_fu_58 <= add_ln103_reg_495;
            end if; 
        end if;
    end process;

    inc512_reg_238_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((visited_q0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15)) or ((icmp_ln149_fu_430_p2 = ap_const_lv1_0) and (visited_load_1_reg_622 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state21)))) then 
                inc512_reg_238 <= inc5139_reg_225;
            elsif (((icmp_ln149_fu_430_p2 = ap_const_lv1_1) and (visited_load_1_reg_622 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state21))) then 
                inc512_reg_238 <= add_ln150_fu_436_p2;
            end if; 
        end if;
    end process;

    inc5139_reg_225_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                inc5139_reg_225 <= ap_phi_mux_inc512_phi_fu_242_p6;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                inc5139_reg_225 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    k_reg_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                k_reg_214 <= add_ln130_reg_594;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                k_reg_214 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln103_reg_495 <= add_ln103_fu_316_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                add_ln126_reg_576 <= add_ln126_fu_368_p2;
                clusters_member_count_addr_reg_586 <= zext_ln126_fu_373_p1(9 - 1 downto 0);
                mul_ln150_reg_581 <= grp_fu_457_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state13) and (icmp_ln125_reg_556 = ap_const_lv1_1) and (visited_load_reg_517 = ap_const_lv1_0))) then
                add_ln130_reg_594 <= add_ln130_fu_383_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln125_fu_354_p2 = ap_const_lv1_1))) then
                cluster_count_0_load_reg_560 <= cluster_count_0_fu_62;
                trunc_ln130_reg_571 <= trunc_ln130_fu_364_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                icmp_ln125_reg_556 <= icmp_ln125_fu_354_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                mul_ln97_2_reg_651 <= grp_fu_411_p2;
                mul_ln98_2_reg_656 <= grp_fu_421_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                mul_ln97_reg_546 <= grp_fu_335_p2;
                mul_ln98_reg_551 <= grp_fu_345_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                neighbor_id_reg_604 <= neighbors_q0;
                visited_addr_1_reg_617 <= zext_ln133_fu_402_p1(9 - 1 downto 0);
                    zext_ln133_reg_610(8 downto 0) <= zext_ln133_fu_402_p1(8 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state16))) then
                reg_285 <= data_q0;
                reg_289 <= sin_values_q0;
                reg_293 <= cos_values_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                trunc_ln103_reg_512 <= trunc_ln103_fu_327_p1;
                visited_load_reg_517 <= visited_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln103_fu_310_p2 = ap_const_lv1_0))) then
                visited_addr_reg_507 <= zext_ln103_fu_322_p1(9 - 1 downto 0);
                    zext_ln103_reg_500(8 downto 0) <= zext_ln103_fu_322_p1(8 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                visited_load_1_reg_622 <= visited_q0;
            end if;
        end if;
    end process;
    zext_ln103_reg_500(63 downto 9) <= "0000000000000000000000000000000000000000000000000000000";
    zext_ln133_reg_610(63 downto 9) <= "0000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, visited_q0, ap_CS_fsm_state2, icmp_ln103_fu_310_p2, ap_CS_fsm_state3, visited_load_reg_517, icmp_ln125_fu_354_p2, icmp_ln125_reg_556, ap_CS_fsm_state9, ap_CS_fsm_state13, icmp_ln130_fu_378_p2, ap_CS_fsm_state15, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_done, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_done, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln103_fu_310_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((visited_q0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln125_fu_354_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state13) and ((visited_load_reg_517 = ap_const_lv1_1) or ((icmp_ln130_fu_378_p2 = ap_const_lv1_1) or (icmp_ln125_reg_556 = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                if (((visited_q0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                if (((grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln103_fu_316_p2 <= std_logic_vector(unsigned(i_fu_58) + unsigned(ap_const_lv9_1));
    add_ln126_fu_368_p2 <= std_logic_vector(unsigned(cluster_count_0_load_reg_560) + unsigned(ap_const_lv32_1));
    add_ln130_fu_383_p2 <= std_logic_vector(unsigned(k_reg_214) + unsigned(ap_const_lv31_1));
    add_ln150_1_fu_447_p2 <= std_logic_vector(signed(mul_ln150_reg_581) + signed(trunc_ln150_1_fu_443_p1));
    add_ln150_fu_436_p2 <= std_logic_vector(unsigned(inc5139_reg_225) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state20_blk_assign_proc : process(grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_done)
    begin
        if ((grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state20_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state20_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_done)
    begin
        if ((grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln103_fu_310_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln103_fu_310_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_inc512_phi_fu_242_p6_assign_proc : process(visited_load_1_reg_622, ap_CS_fsm_state21, inc5139_reg_225, add_ln150_fu_436_p2, inc512_reg_238, icmp_ln149_fu_430_p2)
    begin
        if (((visited_load_1_reg_622 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state21))) then
            if ((icmp_ln149_fu_430_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_inc512_phi_fu_242_p6 <= inc5139_reg_225;
            elsif ((icmp_ln149_fu_430_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_inc512_phi_fu_242_p6 <= add_ln150_fu_436_p2;
            else 
                ap_phi_mux_inc512_phi_fu_242_p6 <= inc512_reg_238;
            end if;
        else 
            ap_phi_mux_inc512_phi_fu_242_p6 <= inc512_reg_238;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln103_fu_310_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln103_fu_310_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= cluster_count_0_fu_62;
    clusters_id_address0 <= zext_ln126_fu_373_p1(9 - 1 downto 0);

    clusters_id_ce0_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            clusters_id_ce0 <= ap_const_logic_1;
        else 
            clusters_id_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    clusters_id_d0 <= trunc_ln103_reg_512;

    clusters_id_we0_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            clusters_id_we0 <= ap_const_logic_1;
        else 
            clusters_id_we0 <= ap_const_logic_0;
        end if; 
    end process;

    clusters_member_count_address0 <= clusters_member_count_addr_reg_586;

    clusters_member_count_ce0_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            clusters_member_count_ce0 <= ap_const_logic_1;
        else 
            clusters_member_count_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    clusters_member_count_d0 <= inc5139_reg_225;

    clusters_member_count_we0_assign_proc : process(visited_load_reg_517, icmp_ln125_reg_556, ap_CS_fsm_state13, icmp_ln130_fu_378_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (icmp_ln130_fu_378_p2 = ap_const_lv1_1) and (icmp_ln125_reg_556 = ap_const_lv1_1) and (visited_load_reg_517 = ap_const_lv1_0))) then 
            clusters_member_count_we0 <= ap_const_logic_1;
        else 
            clusters_member_count_we0 <= ap_const_logic_0;
        end if; 
    end process;

    clusters_members_address0 <= zext_ln150_fu_452_p1(17 - 1 downto 0);

    clusters_members_ce0_assign_proc : process(ap_CS_fsm_state21)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            clusters_members_ce0 <= ap_const_logic_1;
        else 
            clusters_members_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    clusters_members_d0 <= neighbor_id_reg_604;

    clusters_members_we0_assign_proc : process(visited_load_1_reg_622, ap_CS_fsm_state21, icmp_ln149_fu_430_p2)
    begin
        if (((icmp_ln149_fu_430_p2 = ap_const_lv1_1) and (visited_load_1_reg_622 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state21))) then 
            clusters_members_we0 <= ap_const_logic_1;
        else 
            clusters_members_we0 <= ap_const_logic_0;
        end if; 
    end process;


    cos_values_address0_assign_proc : process(zext_ln103_reg_500, ap_CS_fsm_state3, zext_ln133_reg_610, ap_CS_fsm_state15, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_cos_values_address0, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_cos_values_address0, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            cos_values_address0 <= zext_ln133_reg_610(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            cos_values_address0 <= zext_ln103_reg_500(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            cos_values_address0 <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_cos_values_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            cos_values_address0 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_cos_values_address0;
        else 
            cos_values_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    cos_values_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state15, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_cos_values_ce0, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_cos_values_ce0, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            cos_values_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            cos_values_ce0 <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_cos_values_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            cos_values_ce0 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_cos_values_ce0;
        else 
            cos_values_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    data_address0_assign_proc : process(zext_ln103_reg_500, ap_CS_fsm_state3, zext_ln133_reg_610, ap_CS_fsm_state15, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_data_address0, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_data_address0, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            data_address0 <= zext_ln133_reg_610(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_address0 <= zext_ln103_reg_500(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            data_address0 <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_data_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            data_address0 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_data_address0;
        else 
            data_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    data_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state15, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_data_ce0, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_data_ce0, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            data_ce0 <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_data_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            data_ce0 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_data_ce0;
        else 
            data_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_start <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_ap_start_reg;
    grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_start <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_ap_start_reg;

    grp_fu_335_ce_assign_proc : process(grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_335_p_ce, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_335_p_ce, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_335_ce <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_335_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_335_ce <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_335_p_ce;
        else 
            grp_fu_335_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_335_p0_assign_proc : process(sext_ln97_fu_331_p1, ap_CS_fsm_state5, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_335_p_din0, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_335_p_din0, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_335_p0 <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_335_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_335_p0 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_335_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_335_p0 <= sext_ln97_fu_331_p1(18 - 1 downto 0);
        else 
            grp_fu_335_p0 <= "XXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_335_p1_assign_proc : process(reg_285, ap_CS_fsm_state5, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_335_p_din1, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_335_p_din1, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_335_p1 <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_335_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_335_p1 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_335_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_335_p1 <= reg_285;
        else 
            grp_fu_335_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_345_ce_assign_proc : process(grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_345_p_ce, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_345_p_ce, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_345_ce <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_345_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_345_ce <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_345_p_ce;
        else 
            grp_fu_345_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_345_p0_assign_proc : process(ap_CS_fsm_state5, sext_ln98_fu_341_p1, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_345_p_din0, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_345_p_din0, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_345_p0 <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_345_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_345_p0 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_345_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_345_p0 <= sext_ln98_fu_341_p1(18 - 1 downto 0);
        else 
            grp_fu_345_p0 <= "XXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_345_p1_assign_proc : process(reg_285, ap_CS_fsm_state5, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_345_p_din1, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_345_p_din1, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_345_p1 <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_fu_345_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_345_p1 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_fu_345_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_345_p1 <= reg_285;
        else 
            grp_fu_345_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_457_p0 <= cluster_count_0_fu_62(17 - 1 downto 0);
    grp_fu_457_p1 <= ap_const_lv17_168(9 - 1 downto 0);

    grp_sqrt_fixed_32_32_s_fu_664_x_assign_proc : process(grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_sqrt_fixed_32_32_s_fu_664_p_din1, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_sqrt_fixed_32_32_s_fu_664_p_din1, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_sqrt_fixed_32_32_s_fu_664_x <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_grp_sqrt_fixed_32_32_s_fu_664_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_sqrt_fixed_32_32_s_fu_664_x <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_grp_sqrt_fixed_32_32_s_fu_664_p_din1;
        else 
            grp_sqrt_fixed_32_32_s_fu_664_x <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln103_fu_310_p2 <= "1" when (i_fu_58 = ap_const_lv9_168) else "0";
    icmp_ln125_fu_354_p2 <= "1" when (signed(grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbor_count_out) > signed(ap_const_lv32_9)) else "0";
    icmp_ln130_fu_378_p2 <= "1" when (k_reg_214 = trunc_ln130_reg_571) else "0";
    icmp_ln149_fu_430_p2 <= "1" when (signed(grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_new_neighbor_count_out) > signed(ap_const_lv32_9)) else "0";

    neighbors_address0_assign_proc : process(ap_CS_fsm_state13, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_address0, ap_CS_fsm_state8, zext_ln130_fu_389_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            neighbors_address0 <= zext_ln130_fu_389_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            neighbors_address0 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_address0;
        else 
            neighbors_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    neighbors_ce0_assign_proc : process(ap_CS_fsm_state13, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_ce0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            neighbors_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            neighbors_ce0 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_ce0;
        else 
            neighbors_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    neighbors_we0_assign_proc : process(grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_we0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            neighbors_we0 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbors_we0;
        else 
            neighbors_we0 <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln97_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_289),32));

        sext_ln98_fu_341_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_293),32));


    sin_values_address0_assign_proc : process(zext_ln103_reg_500, ap_CS_fsm_state3, zext_ln133_reg_610, ap_CS_fsm_state15, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_sin_values_address0, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_sin_values_address0, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            sin_values_address0 <= zext_ln133_reg_610(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            sin_values_address0 <= zext_ln103_reg_500(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            sin_values_address0 <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_sin_values_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            sin_values_address0 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_sin_values_address0;
        else 
            sin_values_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    sin_values_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state15, grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_sin_values_ce0, grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_sin_values_ce0, ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            sin_values_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            sin_values_ce0 <= grp_dbscan_Pipeline_VITIS_LOOP_137_4_fu_268_sin_values_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            sin_values_ce0 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_sin_values_ce0;
        else 
            sin_values_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln103_fu_327_p1 <= cluster_count_0_fu_62(5 - 1 downto 0);
    trunc_ln130_fu_364_p1 <= grp_dbscan_Pipeline_VITIS_LOOP_113_2_fu_253_neighbor_count_out(31 - 1 downto 0);
    trunc_ln150_1_fu_443_p1 <= inc5139_reg_225(17 - 1 downto 0);

    visited_address0_assign_proc : process(ap_CS_fsm_state2, zext_ln103_fu_322_p1, visited_addr_reg_507, ap_CS_fsm_state3, ap_CS_fsm_state14, zext_ln133_fu_402_p1, visited_addr_1_reg_617, ap_CS_fsm_state15, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state15))) then 
            visited_address0 <= visited_addr_1_reg_617;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            visited_address0 <= zext_ln133_fu_402_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            visited_address0 <= visited_addr_reg_507;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            visited_address0 <= zext_ln103_fu_322_p1(9 - 1 downto 0);
        else 
            visited_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    visited_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            visited_ce0 <= ap_const_logic_1;
        else 
            visited_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    visited_d0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state15, ap_CS_fsm_state21)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            visited_d0 <= ap_const_lv1_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            visited_d0 <= ap_const_lv1_1;
        else 
            visited_d0 <= "X";
        end if; 
    end process;


    visited_we0_assign_proc : process(visited_q0, ap_CS_fsm_state3, visited_load_1_reg_622, ap_CS_fsm_state15, ap_CS_fsm_state21, icmp_ln149_fu_430_p2)
    begin
        if ((((icmp_ln149_fu_430_p2 = ap_const_lv1_0) and (visited_load_1_reg_622 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state21)) or ((visited_q0 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state15)) or ((visited_q0 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            visited_we0 <= ap_const_logic_1;
        else 
            visited_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln103_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_58),64));
    zext_ln126_fu_373_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cluster_count_0_load_reg_560),64));
    zext_ln130_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_reg_214),64));
    zext_ln133_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(neighbors_q0),64));
    zext_ln150_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln150_1_fu_447_p2),64));
end behav;
