-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity clusterOp is
generic (
    C_S_AXI_CTRL_BUS_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CTRL_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    inStream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    inStream_TVALID : IN STD_LOGIC;
    inStream_TREADY : OUT STD_LOGIC;
    inStream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    inStream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    inStream_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    inStream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    inStream_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    inStream_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    outStream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    outStream_TVALID : OUT STD_LOGIC;
    outStream_TREADY : IN STD_LOGIC;
    outStream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    outStream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    outStream_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
    outStream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    outStream_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    outStream_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0);
    s_axi_CTRL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of clusterOp is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "clusterOp_clusterOp,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.289300,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=121,HLS_SYN_DSP=0,HLS_SYN_FF=20385,HLS_SYN_LUT=15754,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (17 downto 0) := "000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (17 downto 0) := "000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (17 downto 0) := "000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (17 downto 0) := "000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (17 downto 0) := "000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (17 downto 0) := "000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (17 downto 0) := "000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (17 downto 0) := "000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (17 downto 0) := "000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (17 downto 0) := "001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (17 downto 0) := "010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv40_0 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv9_168 : STD_LOGIC_VECTOR (8 downto 0) := "101101000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv40_168 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000101101000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv17_168 : STD_LOGIC_VECTOR (16 downto 0) := "00000000101101000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal add_ln33_fu_345_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln33_reg_489 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln33_fu_351_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln33_reg_494 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln33_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grouped_addr_reg_499 : STD_LOGIC_VECTOR (8 downto 0);
    signal cluster_count_load_reg_518 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal trunc_ln33_fu_366_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln33_reg_523 : STD_LOGIC_VECTOR (4 downto 0);
    signal grouped_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grouped_load_reg_528 : STD_LOGIC_VECTOR (0 downto 0);
    signal distances_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal distances_load_reg_542 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fu_456_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln37_reg_547 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal trunc_ln66_fu_408_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln66_reg_552 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal icmp_ln66_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal clusters_member_count_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal clusters_member_count_load_reg_570 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal sub89_fu_450_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub89_reg_575 : STD_LOGIC_VECTOR (31 downto 0);
    signal clusters_id_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal clusters_id_load_reg_580 : STD_LOGIC_VECTOR (4 downto 0);
    signal distances_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal distances_ce0 : STD_LOGIC;
    signal distances_we0 : STD_LOGIC;
    signal grouped_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grouped_ce0 : STD_LOGIC;
    signal grouped_we0 : STD_LOGIC;
    signal grouped_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal clusters_id_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal clusters_id_ce0 : STD_LOGIC;
    signal clusters_id_we0 : STD_LOGIC;
    signal clusters_members_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal clusters_members_ce0 : STD_LOGIC;
    signal clusters_members_we0 : STD_LOGIC;
    signal clusters_members_d0 : STD_LOGIC_VECTOR (8 downto 0);
    signal clusters_members_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal clusters_member_count_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal clusters_member_count_ce0 : STD_LOGIC;
    signal clusters_member_count_we0 : STD_LOGIC;
    signal grp_clusterOp_Pipeline_1_fu_239_ap_start : STD_LOGIC;
    signal grp_clusterOp_Pipeline_1_fu_239_ap_done : STD_LOGIC;
    signal grp_clusterOp_Pipeline_1_fu_239_ap_idle : STD_LOGIC;
    signal grp_clusterOp_Pipeline_1_fu_239_ap_ready : STD_LOGIC;
    signal grp_clusterOp_Pipeline_1_fu_239_grouped_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_clusterOp_Pipeline_1_fu_239_grouped_ce0 : STD_LOGIC;
    signal grp_clusterOp_Pipeline_1_fu_239_grouped_we0 : STD_LOGIC;
    signal grp_clusterOp_Pipeline_1_fu_239_grouped_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_start : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_done : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_idle : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_ready : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_inStream_TREADY : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_ce0 : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_we0 : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_start : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_done : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_idle : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_ready : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_ce0 : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_we0 : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_distances_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_distances_ce0 : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_ce0 : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_we0 : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_d0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_p_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_p_out_ap_vld : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_start : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_done : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_idle : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_ready : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TREADY : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_clusters_members_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_clusters_members_ce0 : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TVALID : STD_LOGIC;
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TUSER : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TID : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TDEST : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_clusterOp_Pipeline_1_fu_239_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal p_loc_fu_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal zext_ln37_fu_385_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln36_fu_389_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal zext_ln66_fu_434_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal put_fu_124 : STD_LOGIC_VECTOR (8 downto 0);
    signal cluster_count_fu_128 : STD_LOGIC_VECTOR (31 downto 0);
    signal cluster_count_1_fu_374_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal phi_mul_fu_156 : STD_LOGIC_VECTOR (39 downto 0);
    signal add_ln66_1_fu_412_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal i_1_fu_160 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln66_fu_428_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln37_fu_385_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln66_1_fu_418_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_456_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_456_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal regslice_both_outStream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal regslice_both_inStream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal inStream_TVALID_int_regslice : STD_LOGIC;
    signal inStream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_inStream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inStream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_inStream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inStream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inStream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_inStream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inStream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inStream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TUSER_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_inStream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inStream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inStream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_inStream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inStream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inStream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TID_int_regslice : STD_LOGIC_VECTOR (4 downto 0);
    signal regslice_both_inStream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inStream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inStream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TDEST_int_regslice : STD_LOGIC_VECTOR (5 downto 0);
    signal regslice_both_inStream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inStream_V_dest_V_U_ack_in : STD_LOGIC;
    signal outStream_TVALID_int_regslice : STD_LOGIC;
    signal outStream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_outStream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outStream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outStream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outStream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outStream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outStream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outStream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outStream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outStream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outStream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outStream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outStream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outStream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outStream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outStream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outStream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outStream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outStream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outStream_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component clusterOp_clusterOp_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        grouped_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        grouped_ce0 : OUT STD_LOGIC;
        grouped_we0 : OUT STD_LOGIC;
        grouped_d0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component clusterOp_clusterOp_Pipeline_VITIS_LOOP_27_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inStream_TVALID : IN STD_LOGIC;
        inStream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        inStream_TREADY : OUT STD_LOGIC;
        inStream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        inStream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        inStream_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
        inStream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        inStream_TID : IN STD_LOGIC_VECTOR (4 downto 0);
        inStream_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
        distances_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        distances_ce0 : OUT STD_LOGIC;
        distances_we0 : OUT STD_LOGIC;
        distances_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component clusterOp_clusterOp_Pipeline_VITIS_LOOP_42_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        grouped_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        grouped_ce0 : OUT STD_LOGIC;
        grouped_we0 : OUT STD_LOGIC;
        grouped_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        grouped_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        put : IN STD_LOGIC_VECTOR (8 downto 0);
        zext_ln33_1 : IN STD_LOGIC_VECTOR (8 downto 0);
        distances_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        distances_ce0 : OUT STD_LOGIC;
        distances_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        distances_load : IN STD_LOGIC_VECTOR (31 downto 0);
        mul_ln37 : IN STD_LOGIC_VECTOR (16 downto 0);
        clusters_members_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        clusters_members_ce0 : OUT STD_LOGIC;
        clusters_members_we0 : OUT STD_LOGIC;
        clusters_members_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out_ap_vld : OUT STD_LOGIC );
    end component;


    component clusterOp_clusterOp_Pipeline_VITIS_LOOP_67_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        outStream_TREADY : IN STD_LOGIC;
        clusters_member_count_load : IN STD_LOGIC_VECTOR (31 downto 0);
        phi_mul : IN STD_LOGIC_VECTOR (16 downto 0);
        clusters_members_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        clusters_members_ce0 : OUT STD_LOGIC;
        clusters_members_q0 : IN STD_LOGIC_VECTOR (8 downto 0);
        sub89 : IN STD_LOGIC_VECTOR (31 downto 0);
        tmp_id_V : IN STD_LOGIC_VECTOR (4 downto 0);
        outStream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        outStream_TVALID : OUT STD_LOGIC;
        outStream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        outStream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        outStream_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
        outStream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        outStream_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
        outStream_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component clusterOp_mul_mul_17s_9ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component clusterOp_distances_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component clusterOp_grouped_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component clusterOp_clusters_id_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (4 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component clusterOp_clusters_members_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (8 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component clusterOp_CTRL_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component clusterOp_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    distances_U : component clusterOp_distances_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 360,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => distances_address0,
        ce0 => distances_ce0,
        we0 => distances_we0,
        d0 => grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_d0,
        q0 => distances_q0);

    grouped_U : component clusterOp_grouped_RAM_AUTO_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 360,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => grouped_address0,
        ce0 => grouped_ce0,
        we0 => grouped_we0,
        d0 => grouped_d0,
        q0 => grouped_q0);

    clusters_id_U : component clusterOp_clusters_id_RAM_AUTO_1R1W
    generic map (
        DataWidth => 5,
        AddressRange => 360,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => clusters_id_address0,
        ce0 => clusters_id_ce0,
        we0 => clusters_id_we0,
        d0 => trunc_ln33_reg_523,
        q0 => clusters_id_q0);

    clusters_members_U : component clusterOp_clusters_members_RAM_AUTO_1R1W
    generic map (
        DataWidth => 9,
        AddressRange => 129600,
        AddressWidth => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => clusters_members_address0,
        ce0 => clusters_members_ce0,
        we0 => clusters_members_we0,
        d0 => clusters_members_d0,
        q0 => clusters_members_q0);

    clusters_member_count_U : component clusterOp_distances_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 360,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => clusters_member_count_address0,
        ce0 => clusters_member_count_ce0,
        we0 => clusters_member_count_we0,
        d0 => p_loc_fu_132,
        q0 => clusters_member_count_q0);

    grp_clusterOp_Pipeline_1_fu_239 : component clusterOp_clusterOp_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_clusterOp_Pipeline_1_fu_239_ap_start,
        ap_done => grp_clusterOp_Pipeline_1_fu_239_ap_done,
        ap_idle => grp_clusterOp_Pipeline_1_fu_239_ap_idle,
        ap_ready => grp_clusterOp_Pipeline_1_fu_239_ap_ready,
        grouped_address0 => grp_clusterOp_Pipeline_1_fu_239_grouped_address0,
        grouped_ce0 => grp_clusterOp_Pipeline_1_fu_239_grouped_ce0,
        grouped_we0 => grp_clusterOp_Pipeline_1_fu_239_grouped_we0,
        grouped_d0 => grp_clusterOp_Pipeline_1_fu_239_grouped_d0);

    grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245 : component clusterOp_clusterOp_Pipeline_VITIS_LOOP_27_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_start,
        ap_done => grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_done,
        ap_idle => grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_idle,
        ap_ready => grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_ready,
        inStream_TVALID => inStream_TVALID_int_regslice,
        inStream_TDATA => inStream_TDATA_int_regslice,
        inStream_TREADY => grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_inStream_TREADY,
        inStream_TKEEP => inStream_TKEEP_int_regslice,
        inStream_TSTRB => inStream_TSTRB_int_regslice,
        inStream_TUSER => inStream_TUSER_int_regslice,
        inStream_TLAST => inStream_TLAST_int_regslice,
        inStream_TID => inStream_TID_int_regslice,
        inStream_TDEST => inStream_TDEST_int_regslice,
        distances_address0 => grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_address0,
        distances_ce0 => grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_ce0,
        distances_we0 => grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_we0,
        distances_d0 => grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_d0);

    grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264 : component clusterOp_clusterOp_Pipeline_VITIS_LOOP_42_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_start,
        ap_done => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_done,
        ap_idle => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_idle,
        ap_ready => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_ready,
        grouped_address0 => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_address0,
        grouped_ce0 => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_ce0,
        grouped_we0 => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_we0,
        grouped_d0 => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_d0,
        grouped_q0 => grouped_q0,
        put => put_fu_124,
        zext_ln33_1 => put_fu_124,
        distances_address0 => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_distances_address0,
        distances_ce0 => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_distances_ce0,
        distances_q0 => distances_q0,
        distances_load => distances_load_reg_542,
        mul_ln37 => mul_ln37_reg_547,
        clusters_members_address0 => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_address0,
        clusters_members_ce0 => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_ce0,
        clusters_members_we0 => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_we0,
        clusters_members_d0 => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_d0,
        p_out => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_p_out,
        p_out_ap_vld => grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_p_out_ap_vld);

    grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300 : component clusterOp_clusterOp_Pipeline_VITIS_LOOP_67_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_start,
        ap_done => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_done,
        ap_idle => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_idle,
        ap_ready => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_ready,
        outStream_TREADY => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TREADY,
        clusters_member_count_load => clusters_member_count_load_reg_570,
        phi_mul => trunc_ln66_reg_552,
        clusters_members_address0 => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_clusters_members_address0,
        clusters_members_ce0 => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_clusters_members_ce0,
        clusters_members_q0 => clusters_members_q0,
        sub89 => sub89_reg_575,
        tmp_id_V => clusters_id_load_reg_580,
        outStream_TDATA => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TDATA,
        outStream_TVALID => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TVALID,
        outStream_TKEEP => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TKEEP,
        outStream_TSTRB => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TSTRB,
        outStream_TUSER => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TUSER,
        outStream_TLAST => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TLAST,
        outStream_TID => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TID,
        outStream_TDEST => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TDEST);

    CTRL_BUS_s_axi_U : component clusterOp_CTRL_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_BUS_AWVALID,
        AWREADY => s_axi_CTRL_BUS_AWREADY,
        AWADDR => s_axi_CTRL_BUS_AWADDR,
        WVALID => s_axi_CTRL_BUS_WVALID,
        WREADY => s_axi_CTRL_BUS_WREADY,
        WDATA => s_axi_CTRL_BUS_WDATA,
        WSTRB => s_axi_CTRL_BUS_WSTRB,
        ARVALID => s_axi_CTRL_BUS_ARVALID,
        ARREADY => s_axi_CTRL_BUS_ARREADY,
        ARADDR => s_axi_CTRL_BUS_ARADDR,
        RVALID => s_axi_CTRL_BUS_RVALID,
        RREADY => s_axi_CTRL_BUS_RREADY,
        RDATA => s_axi_CTRL_BUS_RDATA,
        RRESP => s_axi_CTRL_BUS_RRESP,
        BVALID => s_axi_CTRL_BUS_BVALID,
        BREADY => s_axi_CTRL_BUS_BREADY,
        BRESP => s_axi_CTRL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_mul_17s_9ns_17_4_1_U76 : component clusterOp_mul_mul_17s_9ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 9,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_456_p0,
        din1 => grp_fu_456_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_456_p2);

    regslice_both_inStream_V_data_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TDATA,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_data_V_U_ack_in,
        data_out => inStream_TDATA_int_regslice,
        vld_out => inStream_TVALID_int_regslice,
        ack_out => inStream_TREADY_int_regslice,
        apdone_blk => regslice_both_inStream_V_data_V_U_apdone_blk);

    regslice_both_inStream_V_keep_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TKEEP,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_keep_V_U_ack_in,
        data_out => inStream_TKEEP_int_regslice,
        vld_out => regslice_both_inStream_V_keep_V_U_vld_out,
        ack_out => inStream_TREADY_int_regslice,
        apdone_blk => regslice_both_inStream_V_keep_V_U_apdone_blk);

    regslice_both_inStream_V_strb_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TSTRB,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_strb_V_U_ack_in,
        data_out => inStream_TSTRB_int_regslice,
        vld_out => regslice_both_inStream_V_strb_V_U_vld_out,
        ack_out => inStream_TREADY_int_regslice,
        apdone_blk => regslice_both_inStream_V_strb_V_U_apdone_blk);

    regslice_both_inStream_V_user_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TUSER,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_user_V_U_ack_in,
        data_out => inStream_TUSER_int_regslice,
        vld_out => regslice_both_inStream_V_user_V_U_vld_out,
        ack_out => inStream_TREADY_int_regslice,
        apdone_blk => regslice_both_inStream_V_user_V_U_apdone_blk);

    regslice_both_inStream_V_last_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TLAST,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_last_V_U_ack_in,
        data_out => inStream_TLAST_int_regslice,
        vld_out => regslice_both_inStream_V_last_V_U_vld_out,
        ack_out => inStream_TREADY_int_regslice,
        apdone_blk => regslice_both_inStream_V_last_V_U_apdone_blk);

    regslice_both_inStream_V_id_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TID,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_id_V_U_ack_in,
        data_out => inStream_TID_int_regslice,
        vld_out => regslice_both_inStream_V_id_V_U_vld_out,
        ack_out => inStream_TREADY_int_regslice,
        apdone_blk => regslice_both_inStream_V_id_V_U_apdone_blk);

    regslice_both_inStream_V_dest_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TDEST,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_dest_V_U_ack_in,
        data_out => inStream_TDEST_int_regslice,
        vld_out => regslice_both_inStream_V_dest_V_U_vld_out,
        ack_out => inStream_TREADY_int_regslice,
        apdone_blk => regslice_both_inStream_V_dest_V_U_apdone_blk);

    regslice_both_outStream_V_data_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TDATA,
        vld_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TVALID,
        ack_in => outStream_TREADY_int_regslice,
        data_out => outStream_TDATA,
        vld_out => regslice_both_outStream_V_data_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_data_V_U_apdone_blk);

    regslice_both_outStream_V_keep_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TKEEP,
        vld_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TVALID,
        ack_in => regslice_both_outStream_V_keep_V_U_ack_in_dummy,
        data_out => outStream_TKEEP,
        vld_out => regslice_both_outStream_V_keep_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_keep_V_U_apdone_blk);

    regslice_both_outStream_V_strb_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TSTRB,
        vld_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TVALID,
        ack_in => regslice_both_outStream_V_strb_V_U_ack_in_dummy,
        data_out => outStream_TSTRB,
        vld_out => regslice_both_outStream_V_strb_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_strb_V_U_apdone_blk);

    regslice_both_outStream_V_user_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TUSER,
        vld_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TVALID,
        ack_in => regslice_both_outStream_V_user_V_U_ack_in_dummy,
        data_out => outStream_TUSER,
        vld_out => regslice_both_outStream_V_user_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_user_V_U_apdone_blk);

    regslice_both_outStream_V_last_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TLAST,
        vld_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TVALID,
        ack_in => regslice_both_outStream_V_last_V_U_ack_in_dummy,
        data_out => outStream_TLAST,
        vld_out => regslice_both_outStream_V_last_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_last_V_U_apdone_blk);

    regslice_both_outStream_V_id_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TID,
        vld_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TVALID,
        ack_in => regslice_both_outStream_V_id_V_U_ack_in_dummy,
        data_out => outStream_TID,
        vld_out => regslice_both_outStream_V_id_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_id_V_U_apdone_blk);

    regslice_both_outStream_V_dest_V_U : component clusterOp_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TDEST,
        vld_in => grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TVALID,
        ack_in => regslice_both_outStream_V_dest_V_U_ack_in_dummy,
        data_out => outStream_TDEST,
        vld_out => regslice_both_outStream_V_dest_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_clusterOp_Pipeline_1_fu_239_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_clusterOp_Pipeline_1_fu_239_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_clusterOp_Pipeline_1_fu_239_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_clusterOp_Pipeline_1_fu_239_ap_ready = ap_const_logic_1)) then 
                    grp_clusterOp_Pipeline_1_fu_239_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_ready = ap_const_logic_1)) then 
                    grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_ready = ap_const_logic_1)) then 
                    grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                    grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_ready = ap_const_logic_1)) then 
                    grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    cluster_count_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                cluster_count_fu_128 <= ap_const_lv32_0;
            elsif (((grouped_q0 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                cluster_count_fu_128 <= cluster_count_1_fu_374_p2;
            end if; 
        end if;
    end process;

    i_1_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln33_fu_339_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                i_1_fu_160 <= ap_const_lv31_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state14) and (icmp_ln66_fu_422_p2 = ap_const_lv1_1))) then 
                i_1_fu_160 <= add_ln66_fu_428_p2;
            end if; 
        end if;
    end process;

    phi_mul_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln33_fu_339_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                phi_mul_fu_156 <= ap_const_lv40_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state14) and (icmp_ln66_fu_422_p2 = ap_const_lv1_1))) then 
                phi_mul_fu_156 <= add_ln66_1_fu_412_p2;
            end if; 
        end if;
    end process;

    put_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                put_fu_124 <= ap_const_lv9_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                put_fu_124 <= add_ln33_reg_489;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_ln33_reg_489 <= add_ln33_fu_345_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                cluster_count_load_reg_518 <= cluster_count_fu_128;
                grouped_load_reg_528 <= grouped_q0;
                trunc_ln33_reg_523 <= trunc_ln33_fu_366_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                clusters_id_load_reg_580 <= clusters_id_q0;
                clusters_member_count_load_reg_570 <= clusters_member_count_q0;
                sub89_reg_575 <= sub89_fu_450_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                distances_load_reg_542 <= distances_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln33_fu_339_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                grouped_addr_reg_499 <= zext_ln33_fu_351_p1(9 - 1 downto 0);
                    zext_ln33_reg_494(8 downto 0) <= zext_ln33_fu_351_p1(8 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                mul_ln37_reg_547 <= grp_fu_456_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_p_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                p_loc_fu_132 <= grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_p_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                trunc_ln66_reg_552 <= trunc_ln66_fu_408_p1;
            end if;
        end if;
    end process;
    zext_ln33_reg_494(63 downto 9) <= "0000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state6, icmp_ln33_fu_339_p2, ap_CS_fsm_state7, grouped_q0, ap_CS_fsm_state14, icmp_ln66_fu_422_p2, grp_clusterOp_Pipeline_1_fu_239_ap_done, grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_done, grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_done, grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state12, ap_CS_fsm_state17, ap_CS_fsm_state18, regslice_both_outStream_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_clusterOp_Pipeline_1_fu_239_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((icmp_ln33_fu_339_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (((grouped_q0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state14 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state14) and (icmp_ln66_fu_422_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state18;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                if (((grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state17;
                end if;
            when ap_ST_fsm_state18 => 
                if (((regslice_both_outStream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln33_fu_345_p2 <= std_logic_vector(unsigned(put_fu_124) + unsigned(ap_const_lv9_1));
    add_ln66_1_fu_412_p2 <= std_logic_vector(unsigned(phi_mul_fu_156) + unsigned(ap_const_lv40_168));
    add_ln66_fu_428_p2 <= std_logic_vector(unsigned(i_1_fu_160) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_done)
    begin
        if ((grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;

    ap_ST_fsm_state17_blk_assign_proc : process(grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_done)
    begin
        if ((grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state17_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state17_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state18_blk_assign_proc : process(regslice_both_outStream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_outStream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state18_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state18_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_clusterOp_Pipeline_1_fu_239_ap_done)
    begin
        if ((grp_clusterOp_Pipeline_1_fu_239_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_done)
    begin
        if ((grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state18, regslice_both_outStream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_outStream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state18, regslice_both_outStream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_outStream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    cluster_count_1_fu_374_p2 <= std_logic_vector(unsigned(cluster_count_fu_128) + unsigned(ap_const_lv32_1));

    clusters_id_address0_assign_proc : process(ap_CS_fsm_state14, zext_ln36_fu_389_p1, ap_CS_fsm_state13, zext_ln66_fu_434_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            clusters_id_address0 <= zext_ln66_fu_434_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            clusters_id_address0 <= zext_ln36_fu_389_p1(9 - 1 downto 0);
        else 
            clusters_id_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    clusters_id_ce0_assign_proc : process(ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            clusters_id_ce0 <= ap_const_logic_1;
        else 
            clusters_id_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    clusters_id_we0_assign_proc : process(grouped_load_reg_528, ap_CS_fsm_state13)
    begin
        if (((grouped_load_reg_528 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            clusters_id_we0 <= ap_const_logic_1;
        else 
            clusters_id_we0 <= ap_const_logic_0;
        end if; 
    end process;


    clusters_member_count_address0_assign_proc : process(ap_CS_fsm_state14, zext_ln36_fu_389_p1, ap_CS_fsm_state13, zext_ln66_fu_434_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            clusters_member_count_address0 <= zext_ln66_fu_434_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            clusters_member_count_address0 <= zext_ln36_fu_389_p1(9 - 1 downto 0);
        else 
            clusters_member_count_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    clusters_member_count_ce0_assign_proc : process(ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            clusters_member_count_ce0 <= ap_const_logic_1;
        else 
            clusters_member_count_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    clusters_member_count_we0_assign_proc : process(grouped_load_reg_528, ap_CS_fsm_state13)
    begin
        if (((grouped_load_reg_528 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            clusters_member_count_we0 <= ap_const_logic_1;
        else 
            clusters_member_count_we0 <= ap_const_logic_0;
        end if; 
    end process;


    clusters_members_address0_assign_proc : process(ap_CS_fsm_state10, grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_address0, grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_clusters_members_address0, ap_CS_fsm_state12, ap_CS_fsm_state17, zext_ln37_fu_385_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            clusters_members_address0 <= zext_ln37_fu_385_p1(17 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            clusters_members_address0 <= grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_clusters_members_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            clusters_members_address0 <= grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_address0;
        else 
            clusters_members_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    clusters_members_ce0_assign_proc : process(ap_CS_fsm_state10, grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_ce0, grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_clusters_members_ce0, ap_CS_fsm_state12, ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            clusters_members_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            clusters_members_ce0 <= grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_clusters_members_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            clusters_members_ce0 <= grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_ce0;
        else 
            clusters_members_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    clusters_members_d0_assign_proc : process(ap_CS_fsm_state10, grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_d0, ap_CS_fsm_state12, put_fu_124)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            clusters_members_d0 <= put_fu_124;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            clusters_members_d0 <= grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_d0;
        else 
            clusters_members_d0 <= "XXXXXXXXX";
        end if; 
    end process;


    clusters_members_we0_assign_proc : process(ap_CS_fsm_state10, grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_we0, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            clusters_members_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            clusters_members_we0 <= grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_clusters_members_we0;
        else 
            clusters_members_we0 <= ap_const_logic_0;
        end if; 
    end process;


    distances_address0_assign_proc : process(zext_ln33_reg_494, ap_CS_fsm_state7, grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_address0, grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_distances_address0, ap_CS_fsm_state4, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            distances_address0 <= zext_ln33_reg_494(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            distances_address0 <= grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_distances_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            distances_address0 <= grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_address0;
        else 
            distances_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    distances_ce0_assign_proc : process(ap_CS_fsm_state7, grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_ce0, grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_distances_ce0, ap_CS_fsm_state4, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            distances_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            distances_ce0 <= grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_distances_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            distances_ce0 <= grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_ce0;
        else 
            distances_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    distances_we0_assign_proc : process(grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            distances_we0 <= grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_distances_we0;
        else 
            distances_we0 <= ap_const_logic_0;
        end if; 
    end process;


    grouped_address0_assign_proc : process(ap_CS_fsm_state6, zext_ln33_fu_351_p1, grouped_addr_reg_499, ap_CS_fsm_state7, grp_clusterOp_Pipeline_1_fu_239_grouped_address0, grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_address0, ap_CS_fsm_state2, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grouped_address0 <= grouped_addr_reg_499;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grouped_address0 <= zext_ln33_fu_351_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grouped_address0 <= grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grouped_address0 <= grp_clusterOp_Pipeline_1_fu_239_grouped_address0;
        else 
            grouped_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    grouped_ce0_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7, grp_clusterOp_Pipeline_1_fu_239_grouped_ce0, grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_ce0, ap_CS_fsm_state2, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grouped_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grouped_ce0 <= grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grouped_ce0 <= grp_clusterOp_Pipeline_1_fu_239_grouped_ce0;
        else 
            grouped_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    grouped_d0_assign_proc : process(ap_CS_fsm_state7, grp_clusterOp_Pipeline_1_fu_239_grouped_d0, grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_d0, ap_CS_fsm_state2, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grouped_d0 <= ap_const_lv1_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grouped_d0 <= grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grouped_d0 <= grp_clusterOp_Pipeline_1_fu_239_grouped_d0;
        else 
            grouped_d0 <= "X";
        end if; 
    end process;


    grouped_we0_assign_proc : process(ap_CS_fsm_state7, grouped_q0, grp_clusterOp_Pipeline_1_fu_239_grouped_we0, grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_we0, ap_CS_fsm_state2, ap_CS_fsm_state12)
    begin
        if (((grouped_q0 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            grouped_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grouped_we0 <= grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_grouped_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grouped_we0 <= grp_clusterOp_Pipeline_1_fu_239_grouped_we0;
        else 
            grouped_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_clusterOp_Pipeline_1_fu_239_ap_start <= grp_clusterOp_Pipeline_1_fu_239_ap_start_reg;
    grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_start <= grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_ap_start_reg;
    grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_start <= grp_clusterOp_Pipeline_VITIS_LOOP_42_3_fu_264_ap_start_reg;
    grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_start <= grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_ap_start_reg;
    grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TREADY <= (outStream_TREADY_int_regslice and ap_CS_fsm_state17);
    grp_fu_456_p0 <= cluster_count_fu_128(17 - 1 downto 0);
    grp_fu_456_p1 <= ap_const_lv17_168(9 - 1 downto 0);
    icmp_ln33_fu_339_p2 <= "1" when (put_fu_124 = ap_const_lv9_168) else "0";
    icmp_ln66_fu_422_p2 <= "1" when (signed(zext_ln66_1_fu_418_p1) < signed(cluster_count_fu_128)) else "0";
    inStream_TREADY <= regslice_both_inStream_V_data_V_U_ack_in;

    inStream_TREADY_int_regslice_assign_proc : process(grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_inStream_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inStream_TREADY_int_regslice <= grp_clusterOp_Pipeline_VITIS_LOOP_27_1_fu_245_inStream_TREADY;
        else 
            inStream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    outStream_TVALID <= regslice_both_outStream_V_data_V_U_vld_out;
    outStream_TVALID_int_regslice <= grp_clusterOp_Pipeline_VITIS_LOOP_67_5_fu_300_outStream_TVALID;
    sub89_fu_450_p2 <= std_logic_vector(unsigned(clusters_member_count_q0) + unsigned(ap_const_lv32_FFFFFFFF));
    trunc_ln33_fu_366_p1 <= cluster_count_fu_128(5 - 1 downto 0);
    trunc_ln66_fu_408_p1 <= phi_mul_fu_156(17 - 1 downto 0);
    zext_ln33_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(put_fu_124),64));
    zext_ln36_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cluster_count_load_reg_518),64));
    zext_ln37_fu_385_p0 <= grp_fu_456_p2;
    zext_ln37_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln37_fu_385_p0),64));
    zext_ln66_1_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_fu_160),32));
    zext_ln66_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_fu_160),64));
end behav;
